# Generated by Django 4.1.1 on 2023-08-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_asignacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="asignacion", name="estado2",),
    ]
