# Generated by Django 4.2.3 on 2024-05-31 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0009_alter_cohorte_estudiante_id_cohorte_and_more'),
        ('modulo_asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='id_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_estudiante_in_asignacion', to='modulo_usuario_rol.estudiante'),
        ),
    ]
