# Generated by Django 4.0 on 2022-06-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modulo_asignacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='id_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
