# Generated by Django 4.0 on 2022-10-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modulo_instancia', '0003_delete_cohorte_estudiante'),
        ('modulo_usuario_rol', '0010_alter_usuario_rol_id_semestre_cohorte_estudiante'),
        ('modulo_asignacion', '0003_alter_asignacion_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignacion_UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
                ('id_semestre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre')),
                ('id_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_UE', to='auth.user')),
            ],
            options={
                'db_table': 'asignacion_UE',
            },
        ),
        migrations.CreateModel(
            name='asignacion_UU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('id_semestre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre')),
                ('id_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_UU', to='auth.user')),
                ('id_usuario_jefe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'asignacion_UU',
            },
        ),
        migrations.DeleteModel(
            name='asignacion',
        ),
    ]
