# Generated by Django 5.0.4 on 2024-05-07 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuario_rol', '0007_alter_firma_tratamiento_datos_id_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(default=None, max_length=200, null=True)),
                ('lugar_adecuado_estudio', models.BooleanField(default=False, null=True)),
                ('ocupacion', models.CharField(default=None, max_length=200, null=True)),
                ('max_lvl_estudio_padre', models.CharField(default=None, max_length=200, null=True)),
                ('max_lvl_estudio_madre', models.CharField(default=None, max_length=200, null=True)),
                ('ingresos_mensuales', models.BigIntegerField(default=None)),
                ('gastos_mensuales', models.BigIntegerField(default=None)),
                ('ingresos_suficientes', models.BooleanField(default=False, null=True)),
                ('cambiar_programa', models.BooleanField(default=False, null=True)),
                ('habilidades_razonamiento', models.CharField(default=None, max_length=200, null=True)),
                ('acceso_computador', models.BooleanField(default=False, null=True)),
                ('acceso_internet', models.BooleanField(default=False, null=True)),
                ('calificacion_prueba_diagnostica', models.BigIntegerField(default=None)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_estudiante_in_datos_prediccion', to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'datos_prediccion',
            },
        ),
    ]
