# Generated by Django 5.0.2 on 2024-05-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ia', '0002_alter_datos_prediccion_table_datos_entrenamiento'),
        ('modulo_usuario_rol', '0007_alter_firma_tratamiento_datos_id_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='encuesta_admitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_matricula', models.CharField(max_length=20)),
                ('EA_Edad', models.FloatField()),
                ('EA_Sexo', models.CharField(max_length=10)),
                ('EA_Pasdenacimiento', models.CharField(max_length=100)),
                ('EA_departamentodenacimiento', models.CharField(max_length=100)),
                ('EA_Municipiodenacimiento', models.CharField(max_length=100)),
                ('EA_Tienealgntipodediscapac', models.CharField(max_length=3)),
                ('EA_Estadocivil', models.CharField(max_length=50)),
                ('EA_Deacuerdoconsuculturapu', models.FloatField()),
                ('EA_Estratodelaresidenciaactu', models.CharField(max_length=3)),
                ('EA_Pasdelaresidenciaactual', models.CharField(max_length=100)),
                ('EA_Departamentodelaresidencia', models.CharField(max_length=100)),
                ('EA_Municipiodelaresidenciaac', models.CharField(max_length=100)),
                ('EA_Consideraustedquetieneun', models.CharField(max_length=3)),
                ('EA_Ocupacindelestudiante', models.CharField(max_length=100)),
                ('EA_Ingresosmensualesdelhogar', models.FloatField()),
                ('EA_GastosmensualesdelhogarG', models.FloatField()),
                ('EA_Mximoniveleducativodelpa', models.CharField(max_length=100)),
                ('EA_Mximoniveleducativodela', models.CharField(max_length=100)),
                ('EA_Consideraquelosingresosd', models.CharField(max_length=3)),
                ('EA_Cuntoshijostiene', models.FloatField()),
                ('EA_Piensaafuturocambiarsede', models.CharField(max_length=3)),
                ('EA_Indiqueycalifiquesushabil', models.CharField(max_length=100)),
                ('EA_Tieneaccesoacomputador', models.CharField(max_length=3)),
                ('EA_TieneaccesoaInternet', models.CharField(max_length=3)),
                ('EA_Facultad', models.CharField(max_length=100)),
                ('CAL_pruebadiagnosticamate', models.CharField(max_length=20)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_estudiante_in_encuesta_admitidos', to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'encuesta_admitidos',
            },
        ),
    ]
