# Generated by Django 5.0.2 on 2024-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ia', '0003_encuesta_admitidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta_admitidos',
            name='EA_Deacuerdoconsuculturapu',
            field=models.CharField(max_length=100),
        ),
    ]
