# Generated by Django 4.1 on 2024-08-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modulo_usuario_rol", "0009_alter_cohorte_estudiante_id_cohorte_and_more"),
        ("modulo_academico", "0002_monitoria_academica"),
    ]

    operations = [
        migrations.CreateModel(
            name="asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "id_estudiante",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_estudiante_in_asistencia",
                        to="modulo_usuario_rol.estudiante",
                    ),
                ),
                (
                    "id_monitoria",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_monitoria_in_asistencia",
                        to="modulo_academico.monitoria_academica",
                    ),
                ),
            ],
        ),
    ]
