# Generated by Django 4.1 on 2024-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_formularios_externos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='check_asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
