# Generated by Django 5.2.4 on 2025-12-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_formularios_externos', '0002_asistencia_check_asistencia'),
        ('modulo_usuario_rol', '0011_estudiante_firma_existe'),
    ]

    operations = [
        migrations.CreateModel(
            name='firma_tratamiento_datos_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id_estudiante', models.CharField(default=None, max_length=100)),
                ('documento', models.BigIntegerField(default=None, null=True, unique=True)),
                ('fecha_firma', models.DateTimeField()),
                ('nombre_firma', models.CharField(default=None, max_length=50)),
                ('correo_firma', models.CharField(default=None, max_length=50)),
                ('autoriza_tratamiento_datos', models.BooleanField(default=False)),
                ('autoriza_tratamiento_imagen', models.BooleanField(default=False)),
                ('id_estudiante', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'firma_tratamiento_datos_temp',
            },
        ),
    ]
