# Generated by Django 4.0 on 2022-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_access', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField()),
            ],
        ),
    ]
