# Generated by Django 4.0 on 2022-06-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_geografico', '0001_initial'),
        ('modulo_usuario_rol', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='usuario_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('id_jefe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jefe', to='modulo_usuario_rol.usuario')),
                ('id_rol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.rol')),
                ('id_semestre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semestre_realizacion', to='modulo_usuario_rol.rol')),
                ('id_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol_usuario', to='modulo_usuario_rol.usuario')),
            ],
            options={
                'db_table': 'usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='rol_permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permiso', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='permiso_por_asignar', to='modulo_usuario_rol.permiso')),
                ('id_rol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='modulo_usuario_rol.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
            },
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc_ini', models.CharField(max_length=30)),
                ('num_doc_ini', models.BigIntegerField()),
                ('tipo_doc', models.CharField(max_length=30)),
                ('dir_ini', models.CharField(max_length=50)),
                ('telefono_ini', models.BigIntegerField()),
                ('dir_res', models.CharField(max_length=50)),
                ('telefono_res', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('acudiente', models.CharField(max_length=100)),
                ('telefono_acudiente', models.BigIntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('colegio', models.CharField(max_length=60)),
                ('estamento', models.CharField(max_length=10)),
                ('estado_ases', models.BooleanField()),
                ('celular', models.BigIntegerField()),
                ('hijos', models.IntegerField()),
                ('barrio_ini', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='barrio_inicial', to='modulo_geografico.barrio')),
                ('barrio_res', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='barrio_actual', to='modulo_geografico.barrio')),
                ('ciudad_ini', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_inicial', to='modulo_geografico.municipio')),
                ('ciudad_res', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_actual', to='modulo_geografico.municipio')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
    ]
