# Generated by Django 4.0 on 2022-06-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modulo_usuario_rol', '0006_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_rol',
            name='id_jefe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jefe', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='usuario_rol',
            name='id_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol_usuario', to='auth.user'),
        ),
    ]
