# Generated by Django 4.0 on 2022-07-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0008_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='num_doc',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='acudiente',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='colegio',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dir_ini',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dir_res',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_ases',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estamento',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='hijos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_acudiente',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_ini',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_res',
            field=models.BigIntegerField(default=None),
        ),
    ]
