# Generated by Django 4.0 on 2022-10-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modulo_usuario_rol', '0010_alter_usuario_rol_id_semestre_cohorte_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_rol',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario_rol',
            name='id_jefe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jefe', to='auth.user'),
        ),
    ]
