# Generated by Django 4.0 on 2022-10-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0011_alter_usuario_rol_estado_alter_usuario_rol_id_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
