# Generated by Django 4.1.1 on 2022-11-23 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_usuario_rol', '0017_alter_estudiante_cod_univalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_rol',
            name='id_jefe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe', to=settings.AUTH_USER_MODEL),
        ),
    ]
