# Generated by Django 4.2 on 2023-05-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_programa', '0002_alter_programa_id_sede_delete_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='programa_estudiante',
            name='estado',
        ),
        migrations.AddField(
            model_name='programa_estudiante',
            name='id_estado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_estado_programa_in_programa_estudiante', to='modulo_programa.estado_programa'),
        ),
    ]
