# Generated by Django 4.1.2 on 2023-06-09 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0022_estudiante_cohorte'),
        ('modulo_instancia', '0006_delete_instancia'),
        ('modulo_programa', '0003_estado_programa_remove_programa_estudiante_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_estado_programa_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Semestre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre')),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_programa.estado_programa')),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
                ('id_programa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_programa.programa')),
                ('id_sede', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.sede')),
            ],
        ),
    ]
