# Generated by Django 4.1.2 on 2023-07-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0029_remove_monitor_vive_con'),
        ('modulo_programa', '0004_historial_estado_programa_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='programa_monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traker', models.BooleanField(default=True)),
                ('id_estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_estado_programa_in_programa_monitor', to='modulo_programa.estado_programa')),
                ('id_monitor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_estudiante_in_programa_monitor', to='modulo_usuario_rol.monitor')),
                ('id_programa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_programa_in_programa_monitor', to='modulo_programa.programa')),
            ],
        ),
    ]
