# Generated by Django 4.2.3 on 2023-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_programa', '0005_programa_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='codigo_univalle',
            field=models.CharField(max_length=2),
        ),
    ]
