# Generated by Django 4.2.3 on 2023-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_programa', '0006_alter_facultad_codigo_univalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='codigo_univalle',
            field=models.BigIntegerField(verbose_name=4),
        ),
    ]
