# Generated by Django 4.2.3 on 2023-08-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_programa', '0007_alter_programa_codigo_univalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
