# Generated by Django 4.1.1 on 2023-10-11 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("modulo_usuario_rol", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="campus_diverso_estamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_estamento", models.CharField(max_length=100, unique=True)),
            ],
            options={"db_table": "campus_diverso_estamento",},
        ),
        migrations.CreateModel(
            name="campus_diverso_expresion_genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_expresion_genero",
                    models.CharField(max_length=200, unique=True),
                ),
            ],
            options={"db_table": "campus_diverso_expresion_genero",},
        ),
        migrations.CreateModel(
            name="campus_diverso_identidad_etnico_racial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_grupo_poblacional",
                    models.CharField(max_length=300, unique=True),
                ),
            ],
            options={"db_table": "campus_diverso_identidad_etnico_racial",},
        ),
        migrations.CreateModel(
            name="campus_diverso_identidad_genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_identidad_genero",
                    models.CharField(max_length=200, unique=True),
                ),
            ],
            options={"db_table": "campus_diverso_identidad_genero",},
        ),
        migrations.CreateModel(
            name="campus_diverso_informacion_general",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("creacion", models.DateTimeField(auto_now_add=True)),
                ("modificacion", models.DateTimeField(auto_now=True)),
                ("dedicacion_externa", models.CharField(max_length=100, null=True)),
                ("tiene_eps", models.CharField(default="Desconocido", max_length=20)),
                (
                    "nombre_eps",
                    models.CharField(default="Sin observacion", max_length=200),
                ),
                ("regimen_eps", models.CharField(default="Sin regimen", max_length=50)),
                ("tipo_entidad_acompanamiento_recibido", models.TextField(null=True)),
                (
                    "calificacion_acompanamiento_recibido",
                    models.IntegerField(null=True),
                ),
                ("motivo_calificacion_acompanamiento", models.TextField(null=True)),
                ("actividades_especificas_tiempo_libre", models.TextField(null=True)),
                (
                    "observacion_general_actividades_especificas_tiempo_libre",
                    models.TextField(null=True),
                ),
                ("observacion_general_fuente_de_ingresos", models.TextField(null=True)),
                ("calificacion_relacion_familiar", models.IntegerField(null=True)),
                ("relacion_familiar", models.IntegerField(null=True)),
                ("observacion_general_redes_de_apoyo", models.TextField(null=True)),
                ("observacion_general_factores_de_riesgo", models.TextField(null=True)),
                ("creencia_religiosa", models.TextField(null=True)),
                (
                    "decision_encuentro_inicial_con_profesional",
                    models.CharField(max_length=30, null=True),
                ),
                ("observacion_horario", models.TextField(default="Sin observación")),
                (
                    "origen_descubrimiento_campus_diverso",
                    models.CharField(max_length=300, null=True),
                ),
                ("comentarios_o_sugerencias_de_usuario", models.TextField(null=True)),
                (
                    "id_creador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_creador_in_campus_diverso_informacion_general",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_modificador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_modificador_in_campus_diverso_informacion_general",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_informacion_general",},
        ),
        migrations.CreateModel(
            name="campus_diverso_ocupacion_actual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_ocupacion_actual",
                    models.CharField(max_length=200, unique=True),
                ),
            ],
            options={"db_table": "campus_diverso_ocupacion_actual",},
        ),
        migrations.CreateModel(
            name="campus_diverso_orientacion_sexual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_orientacion_sexual",
                    models.CharField(max_length=200, unique=True),
                ),
            ],
            options={"db_table": "campus_diverso_orientacion_sexual",},
        ),
        migrations.CreateModel(
            name="campus_diverso_persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incluir_correo_en_respuesta", models.BooleanField(default=False)),
                ("nombre_identitario", models.CharField(max_length=150)),
                ("estrato_socioeconomico", models.IntegerField()),
                (
                    "ciudad_nacimiento",
                    models.CharField(default="Ciudad no especificada", max_length=100),
                ),
                (
                    "corregimiento_nacimiento",
                    models.CharField(
                        default="Corregimiento no especificado", max_length=100
                    ),
                ),
                ("departamento_nacimiento", models.CharField(max_length=100)),
                ("pais_nacimiento", models.CharField(max_length=100)),
                (
                    "ciudad_residencia",
                    models.CharField(default="Ciudad no especificada", max_length=100),
                ),
                (
                    "corregimiento_residencia",
                    models.CharField(
                        default="Corregimiento no especificado", max_length=100
                    ),
                ),
                ("zona_residencial", models.CharField(max_length=100)),
                ("direccion_residencia", models.CharField(max_length=200)),
                ("barrio_residencia", models.CharField(max_length=150)),
                ("comuna_barrio", models.CharField(max_length=20)),
                ("nombre_persona_de_confianza", models.CharField(max_length=100)),
                ("telefono_persona_de_confianza", models.CharField(max_length=100)),
                (
                    "identidad_etnico_racial",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identidad_etnico_racial_in_campus_diverso_persona",
                        to="modulo_campus_diverso.campus_diverso_identidad_etnico_racial",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_persona",},
        ),
        migrations.CreateModel(
            name="campus_diverso_persona_estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_estudiante",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_estudiante_in_campus_diverso_persona_estudiante",
                        to="modulo_usuario_rol.estudiante",
                    ),
                ),
                (
                    "id_persona",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_persona_in_campus_diverso_persona_estudiante",
                        to="modulo_campus_diverso.campus_diverso_persona",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_persona_estudiante",},
        ),
        migrations.CreateModel(
            name="campus_diverso_pertenencia_grupo_poblacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_grupo_poblacional",
                    models.CharField(max_length=300, unique=True),
                ),
            ],
            options={"db_table": "campus_diverso_pertenencia_grupo_poblacional",},
        ),
        migrations.CreateModel(
            name="campus_diverso_pronombre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_pronombre", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "campus_diverso_pronombre",},
        ),
        migrations.CreateModel(
            name="campus_diverso_relacion_persona_de_confianza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_grupo_poblacional",
                    models.CharField(max_length=300, unique=True),
                ),
            ],
            options={"db_table": "campus_diverso_relacion_persona_de_confianza",},
        ),
        migrations.CreateModel(
            name="campus_diverso_respuesta_cambio_documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_respuesta_cambio_documento", models.TextField(unique=True)),
            ],
            options={"db_table": "campus_diverso_respuesta_cambio_documento",},
        ),
        migrations.CreateModel(
            name="campus_diverso_seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creacion", models.DateTimeField(auto_now_add=True)),
                ("modificacion", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField()),
                (
                    "id_creador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_creador_in_campus_diverso_seguimiento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_modificador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_modificador_in_campus_diverso_seguimiento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="modulo_campus_diverso.campus_diverso_persona_estudiante",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_seguimiento",},
        ),
        migrations.CreateModel(
            name="campus_diverso_red_apoyo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_red_apoyo", models.CharField(max_length=200)),
                (
                    "observacion_red_apoyo",
                    models.TextField(blank=True, default="Sin observacion"),
                ),
                (
                    "id_informacion_general",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_informacion_general_in_campus_diverso_red_de_apoyo",
                        to="modulo_campus_diverso.campus_diverso_informacion_general",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_red_apoyo",},
        ),
        migrations.AddField(
            model_name="campus_diverso_persona",
            name="pertenencia_grupo_poblacional",
            field=models.ManyToManyField(
                max_length=300,
                related_name="pertenencia_grupo_poblacional_in_campus_diverso_persona",
                to="modulo_campus_diverso.campus_diverso_pertenencia_grupo_poblacional",
            ),
        ),
        migrations.AddField(
            model_name="campus_diverso_persona",
            name="relacion_persona_de_confianza",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relacion_persona_de_confianza_in_campus_diverso_persona",
                to="modulo_campus_diverso.campus_diverso_relacion_persona_de_confianza",
            ),
        ),
        migrations.AddField(
            model_name="campus_diverso_informacion_general",
            name="id_persona",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_persona_in_campus_diverso_informacion_general",
                to="modulo_campus_diverso.campus_diverso_persona_estudiante",
            ),
        ),
        migrations.AddField(
            model_name="campus_diverso_informacion_general",
            name="ocupaciones_actuales",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_ocupaciones_actuales",
                to="modulo_campus_diverso.campus_diverso_ocupacion_actual",
            ),
        ),
        migrations.CreateModel(
            name="campus_diverso_informacion_academica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pertenencia_univalle", models.BooleanField()),
                ("sede_universidad", models.CharField(max_length=20)),
                ("nombre_programa_academico", models.CharField(max_length=100)),
                ("semestre_academico", models.IntegerField()),
                (
                    "estamentos",
                    models.ManyToManyField(
                        max_length=100,
                        related_name="id_informacion_academica",
                        to="modulo_campus_diverso.campus_diverso_estamento",
                    ),
                ),
                (
                    "id_persona_estudiante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_persona_in_campus_diverso_informacion_academica",
                        to="modulo_campus_diverso.campus_diverso_persona_estudiante",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_informacion_academica",},
        ),
        migrations.CreateModel(
            name="campus_diverso_fuente_ingresos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_fuente_ingresos", models.CharField(max_length=200)),
                (
                    "observacion_fuente_ingresos",
                    models.TextField(blank=True, default="Sin Observación"),
                ),
                (
                    "id_informacion_general",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_informacion_general_in_campus_diverso_fuente_ingresos",
                        to="modulo_campus_diverso.campus_diverso_informacion_general",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_fuente_ingresos",},
        ),
        migrations.CreateModel(
            name="campus_diverso_factor_riesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_factor_riesgo", models.CharField(max_length=200)),
                (
                    "observacion_factor_riesgo",
                    models.TextField(blank=True, default="Sin observacion"),
                ),
                (
                    "id_informacion_general",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_informacion_general_in_campus_diverso_factores_de_riesgo",
                        to="modulo_campus_diverso.campus_diverso_informacion_general",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_factor_riesgo",},
        ),
        migrations.CreateModel(
            name="campus_diverso_documentos_autorizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autorizacion_manejo_de_datos", models.BooleanField()),
                ("firma_consentimiento_informado", models.BooleanField()),
                ("firma_terapia_hormonal", models.BooleanField(blank=True, null=True)),
                (
                    "documento_digital_y_archivo",
                    models.BooleanField(blank=True, null=True),
                ),
                ("apgar_familiar", models.IntegerField(null=True)),
                ("ecomapa", models.BooleanField(blank=True, null=True)),
                ("arbol_familiar", models.BooleanField(blank=True, null=True)),
                (
                    "id_persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_persona_in_campus_diverso_documentos_autorizacion",
                        to="modulo_campus_diverso.campus_diverso_persona_estudiante",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_documentos_autorizacion",},
        ),
        migrations.CreateModel(
            name="campus_diverso_diversidad_sexual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cambio_nombre_sexo_documento", models.CharField(max_length=50)),
                ("recibir_orientacion_cambio_en_documento", models.BooleanField()),
                (
                    "expresiones_de_genero",
                    models.ManyToManyField(
                        max_length=200,
                        to="modulo_campus_diverso.campus_diverso_expresion_genero",
                    ),
                ),
                (
                    "id_persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DiversidadSexual",
                        to="modulo_campus_diverso.campus_diverso_persona",
                    ),
                ),
                (
                    "identidades_de_genero",
                    models.ManyToManyField(
                        max_length=200,
                        to="modulo_campus_diverso.campus_diverso_identidad_genero",
                    ),
                ),
                (
                    "orientaciones_sexuales",
                    models.ManyToManyField(
                        max_length=200,
                        to="modulo_campus_diverso.campus_diverso_orientacion_sexual",
                    ),
                ),
                (
                    "pronombres",
                    models.ManyToManyField(
                        max_length=50,
                        to="modulo_campus_diverso.campus_diverso_pronombre",
                    ),
                ),
                (
                    "respuestas_cambio_documento",
                    models.ManyToManyField(
                        to="modulo_campus_diverso.campus_diverso_respuesta_cambio_documento"
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_diversidad_sexual",},
        ),
        migrations.CreateModel(
            name="campus_diverso_convivencia_vivienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_convivencia_vivienda", models.CharField(max_length=200)),
                (
                    "observacion_convivencia_vivienda",
                    models.TextField(blank=True, default="Sin observacion"),
                ),
                (
                    "id_informacion_general",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_informacion_general_in_campus_diverso_convivencias_en_vivienda",
                        to="modulo_campus_diverso.campus_diverso_informacion_general",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_convivencia_vivienda",},
        ),
        migrations.CreateModel(
            name="campus_diverso_actividad_tiempo_libre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_actividad_tiempo_libre", models.CharField(max_length=200)),
                (
                    "observacion_actividad_tiempo_libre",
                    models.TextField(blank=True, default="Sin observación"),
                ),
                (
                    "id_informacion_general",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_informacion_general_in_campus_diverso_actividad_tiempo_libre",
                        to="modulo_campus_diverso.campus_diverso_informacion_general",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_actividad_tiempo_libre",},
        ),
        migrations.CreateModel(
            name="campus_diverso_acompañamiento_recibido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_acompañamiento_recibido", models.CharField(max_length=200)),
                (
                    "observacion_acompanamiento_recibido",
                    models.TextField(blank=True, default="Sin observaciones"),
                ),
                (
                    "id_informacion_general",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_informacion_general_in_campus_diverso_acompañamiento_recibido",
                        to="modulo_campus_diverso.campus_diverso_informacion_general",
                    ),
                ),
            ],
            options={"db_table": "campus_diverso_acompañamiento_recibido",},
        ),
    ]
