# Generated by Django 4.2.6 on 2023-10-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus_diverso_identidad_etnico_racial',
            old_name='nombre_grupo_poblacional',
            new_name='nombre_identidad_etnico_racial',
        ),
        migrations.RenameField(
            model_name='campus_diverso_relacion_persona_de_confianza',
            old_name='nombre_grupo_poblacional',
            new_name='nombre_persona_confianza',
        ),
    ]
