# Generated by Django 4.2.6 on 2023-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0002_rename_nombre_grupo_poblacional_campus_diverso_identidad_etnico_racial_nombre_identidad_etnico_racia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus_diverso_persona',
            name='identidad_etnico_racial',
        ),
        migrations.RemoveField(
            model_name='campus_diverso_persona',
            name='relacion_persona_de_confianza',
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='identidad_etnico_racial',
            field=models.ManyToManyField(default=None, max_length=300, null=True, related_name='identidad_etnico_racial_in_campus_diverso_persona', to='modulo_campus_diverso.campus_diverso_identidad_etnico_racial'),
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='relacion_persona_de_confianza',
            field=models.ManyToManyField(default=None, max_length=300, null=True, related_name='relacion_persona_de_confianza_in_campus_diverso_persona', to='modulo_campus_diverso.campus_diverso_relacion_persona_de_confianza'),
        ),
    ]
