# Generated by Django 4.2.6 on 2023-10-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0003_remove_campus_diverso_persona_identidad_etnico_racial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_diverso_diversidad_sexual',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_in_campus_diverso_diversidad_sexual', to='modulo_campus_diverso.campus_diverso_persona'),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='identidad_etnico_racial',
            field=models.ManyToManyField(max_length=300, related_name='identidad_etnico_racial_in_campus_diverso_persona', to='modulo_campus_diverso.campus_diverso_identidad_etnico_racial'),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='relacion_persona_de_confianza',
            field=models.ManyToManyField(max_length=300, related_name='relacion_persona_de_confianza_in_campus_diverso_persona', to='modulo_campus_diverso.campus_diverso_relacion_persona_de_confianza'),
        ),
    ]
