# Generated by Django 4.2.6 on 2023-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0004_alter_campus_diverso_diversidad_sexual_id_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus_diverso_persona',
            name='direccion_residencia',
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='estado_civil',
            field=models.CharField(default='Sin respuesta', max_length=100),
        ),
    ]
