# Generated by Django 4.2.6 on 2023-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0005_remove_campus_diverso_persona_direccion_residencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='apellido',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='cod_univalle',
            field=models.IntegerField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='fecha_nac',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='nombre',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='num_doc',
            field=models.IntegerField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='telefono_res',
            field=models.IntegerField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='campus_diverso_persona',
            name='tipo_doc',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='campus_diverso_diversidad_sexual',
            name='cambio_nombre_sexo_documento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campus_diverso_informacion_general',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='estrato_socioeconomico',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='identidad_etnico_racial',
            field=models.ManyToManyField(default='no responde', max_length=300, related_name='identidad_etnico_racial_in_campus_diverso_persona', to='modulo_campus_diverso.campus_diverso_identidad_etnico_racial'),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='pertenencia_grupo_poblacional',
            field=models.ManyToManyField(default='no responde', max_length=300, related_name='pertenencia_grupo_poblacional_in_campus_diverso_persona', to='modulo_campus_diverso.campus_diverso_pertenencia_grupo_poblacional'),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='relacion_persona_de_confianza',
            field=models.ManyToManyField(default='no responde', max_length=300, related_name='relacion_persona_de_confianza_in_campus_diverso_persona', to='modulo_campus_diverso.campus_diverso_relacion_persona_de_confianza'),
        ),
    ]
