# Generated by Django 4.2.6 on 2023-10-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0006_campus_diverso_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=150),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='cod_univalle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='nombre',
            field=models.CharField(default='No da nombre', max_length=150),
        ),
    ]
