# Generated by Django 4.2.6 on 2023-10-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0007_alter_campus_diverso_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_diverso_diversidad_sexual',
            name='cambio_nombre_sexo_documento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campus_diverso_diversidad_sexual',
            name='recibir_orientacion_cambio_en_documento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='estrato_socioeconomico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='num_doc',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='campus_diverso_persona',
            name='telefono_res',
            field=models.IntegerField(default=None),
        ),
    ]
