# Generated by Django 4.1.1 on 2022-11-23 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_usuario_rol", "0017_alter_estudiante_cod_univalle"),
        ("modulo_carga_masiva", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retiro",
            name="id_estudiante",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_estudiante_in_retiro",
                to="modulo_usuario_rol.estudiante",
            ),
        ),
    ]
