# Generated by Django 4.2.1 on 2023-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiversidadSexual',
            fields=[
                ('id_diversidad_sexual', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(max_length=30, unique=True)),
                ('expresion_genero', models.CharField(max_length=100)),
                ('cambio_nombre_sexo_documento', models.CharField(max_length=50)),
                ('recibir_orientacion_cambio_en_documento', models.BooleanField()),
            ],
            options={
                'db_table': 'Diversidad_sexual',
            },
        ),
    ]
