# Generated by Django 4.2.1 on 2023-06-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversidad_sexual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diversidadsexual',
            name='expresion_genero',
        ),
    ]
