# Generated by Django 4.2.1 on 2023-06-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0004_remove_persona_pertenencia_grupo_poblacional'),
        ('app_diversidad_sexual', '0002_remove_diversidadsexual_expresion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversidadsexual',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_registro.persona'),
        ),
    ]
