# Generated by Django 4.2.1 on 2023-06-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversidad_sexual', '0003_alter_diversidadsexual_id_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronombre',
            fields=[
                ('id_pronombre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pronombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='diversidadsexual',
            name='pronombres',
            field=models.ManyToManyField(max_length=50, to='app_diversidad_sexual.pronombre'),
        ),
    ]
