# Generated by Django 4.2.1 on 2023-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversidad_sexual', '0004_pronombre_diversidadsexual_pronombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadGenero',
            fields=[
                ('id_identidad_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_identidad_genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='diversidadsexual',
            name='identidades_de_genero',
            field=models.ManyToManyField(max_length=200, to='app_diversidad_sexual.identidadgenero'),
        ),
    ]
