# Generated by Django 4.2.1 on 2023-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversidad_sexual', '0006_expresiongenero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientacionSexual',
            fields=[
                ('id_orientacion_sexual', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_orientacion_sexual', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='diversidadsexual',
            name='orientaciones_sexuales',
            field=models.ManyToManyField(max_length=200, to='app_diversidad_sexual.orientacionsexual'),
        ),
    ]
