# Generated by Django 4.2.1 on 2023-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversidad_sexual', '0007_orientacionsexual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaCambioDocumento',
            fields=[
                ('id_respuesta_cambio_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_respuesta_cambio_documento', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='diversidadsexual',
            name='respuestas_cambio_documento',
            field=models.ManyToManyField(to='app_diversidad_sexual.respuestacambiodocumento'),
        ),
    ]
