# Generated by Django 4.2.13 on 2024-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversidad_sexual', '0010_alter_diversidadsexual_cambio_nombre_sexo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversidadsexual',
            name='cambio_nombre_sexo_documento',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='diversidadsexual',
            name='pronombres',
            field=models.ManyToManyField(blank=True, max_length=100, to='app_diversidad_sexual.pronombre'),
        ),
        migrations.AlterField(
            model_name='diversidadsexual',
            name='respuestas_cambio_documento',
            field=models.ManyToManyField(blank=True, to='app_diversidad_sexual.respuestacambiodocumento'),
        ),
    ]
