# Generated by Django 5.0.7 on 2025-03-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diversidad_sexual', '0011_alter_diversidadsexual_cambio_nombre_sexo_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diversidadsexual',
            name='cambio_nombre_sexo_documento',
        ),
    ]
