# Generated by Django 4.1.1 on 2022-11-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historial_academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_semestral', models.DecimalField(decimal_places=2, max_digits=3)),
                ('promedio_acumulado', models.DecimalField(decimal_places=2, max_digits=3)),
                ('json_materias', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_materia', models.CharField(default=None, max_length=20)),
                ('nombre', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
