# Generated by Django 4.1.1 on 2022-11-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_academico', '0001_initial'),
        ('modulo_instancia', '0004_semestre_estado'),
        ('modulo_programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_academico',
            name='id_programa_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_programa_estudiante_in_historial_academico', to='modulo_programa.programa_estudiante'),
        ),
        migrations.AddField(
            model_name='historial_academico',
            name='id_semestre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_semestre_in_historial_academico', to='modulo_instancia.semestre'),
        ),
    ]
