# Generated by Django 4.1.1 on 2023-10-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modulo_geografico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="cohorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=50)),
                ("tiempo_creacion", models.DateTimeField(auto_now_add=True)),
                ("tiempo_modificacion", models.DateTimeField()),
            ],
            options={"db_table": "cohorte",},
        ),
        migrations.CreateModel(
            name="sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_univalle", models.BigIntegerField()),
                ("nombre", models.CharField(max_length=50)),
                (
                    "id_municipio",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_municipio_in_sede",
                        to="modulo_geografico.municipio",
                    ),
                ),
            ],
            options={"db_table": "sede",},
        ),
        migrations.CreateModel(
            name="semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("semestre_actual", models.BooleanField(default=False)),
                ("estado", models.SmallIntegerField(default=0)),
                (
                    "id_sede",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modulo_instancia.sede",
                    ),
                ),
            ],
            options={"db_table": "semestre",},
        ),
        migrations.CreateModel(
            name="cohorte_sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_cohorte",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modulo_instancia.cohorte",
                    ),
                ),
                (
                    "id_sede",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modulo_instancia.sede",
                    ),
                ),
            ],
            options={"db_table": "cohorte_sede",},
        ),
    ]
