# Generated by Django 4.0 on 2022-06-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_modificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'cohorte',
            },
        ),
        migrations.CreateModel(
            name='instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'instancia',
            },
        ),
        migrations.CreateModel(
            name='semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('semestre_actual', models.BooleanField(default=False)),
                ('id_instancia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.instancia')),
            ],
            options={
                'db_table': 'semestre',
            },
        ),
        migrations.CreateModel(
            name='cohorte_instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cohorte', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.cohorte')),
                ('id_instancia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.instancia')),
            ],
            options={
                'db_table': 'cohorte_instancia',
            },
        ),
        migrations.CreateModel(
            name='cohorte_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cohorte', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.cohorte')),
            ],
            options={
                'db_table': 'cohorte_estudiante',
            },
        ),
    ]
