# Generated by Django 5.1.1 on 2026-02-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
