# Generated by Django 4.1.1 on 2023-05-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_geografico", "0001_initial"),
        ("modulo_instancia", "0004_semestre_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_univalle", models.BigIntegerField()),
                ("nombre", models.CharField(max_length=50)),
                (
                    "id_municipio",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_municipio_in_sede",
                        to="modulo_geografico.municipio",
                    ),
                ),
            ],
            options={"db_table": "sede",},
        ),
        migrations.RenameModel(old_name="cohorte_instancia", new_name="cohorte_sede",),
        migrations.AlterModelTable(name="cohorte_sede", table="cohorte_sede",),
        migrations.RemoveField(model_name="cohorte_sede", name="id_instancia",),
        migrations.RemoveField(model_name="semestre", name="id_instancia",),
        migrations.AddField(
            model_name="cohorte_sede",
            name="id_sede",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="modulo_instancia.sede",
            ),
        ),
        migrations.AddField(
            model_name="semestre",
            name="id_sede",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="modulo_instancia.sede",
            ),
        ),
    ]
