# Generated by Django 4.1.1 on 2023-05-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_instancia", "0005_sede_remove_cohorte_sede_id_instancia_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="instancia",),
    ]
