# Generated by Django 4.2.3 on 2023-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0006_delete_instancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
    ]
