# Generated by Django 4.2.3 on 2023-08-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0007_alter_cohorte_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
