# Generated by Django 4.2.1 on 2023-06-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_registro', '0005_remove_pertenenciagrupopoblacional_personas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionAcademica',
            fields=[
                ('id_informacion_academica', models.AutoField(primary_key=True, serialize=False)),
                ('pertenencia_univalle', models.BooleanField()),
                ('sede_universidad', models.CharField(max_length=20)),
                ('nombre_programa_academico', models.CharField(max_length=100)),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True)),
                ('semestre_academico', models.IntegerField()),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_registro.persona')),
            ],
        ),
    ]
