# Generated by Django 4.2.1 on 2023-06-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_academica', '0002_estamento_informacionacademica_estamentos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='informacionacademica',
            table='Informacion_academica',
        ),
    ]
