# Generated by Django 4.2.13 on 2024-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_academica', '0005_alter_informacionacademica_nombre_programa_academico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionacademica',
            name='estamentos',
            field=models.ManyToManyField(blank=True, max_length=100, to='app_informacion_academica.estamento'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='nombre_programa_academico',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='sede_universidad',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='semestre_academico',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
