# Generated by Django 4.2.13 on 2024-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_academica', '0006_alter_informacionacademica_estamentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionacademica',
            name='codigo_estudiante',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
