# Generated by Django 5.0.7 on 2024-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_academica', '0007_alter_informacionacademica_codigo_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombrePrograma',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SedeUniversidad',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='informacionacademica',
            name='nombre_programa_academico',
        ),
        migrations.RemoveField(
            model_name='informacionacademica',
            name='sede_universidad',
        ),
        migrations.AddField(
            model_name='informacionacademica',
            name='programas',
            field=models.ManyToManyField(blank=True, max_length=200, to='app_informacion_academica.nombreprograma'),
        ),
        migrations.AddField(
            model_name='informacionacademica',
            name='sedes',
            field=models.ManyToManyField(blank=True, max_length=200, to='app_informacion_academica.sedeuniversidad'),
        ),
    ]
