# Generated by Django 5.2 on 2025-05-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_academica', '0008_nombreprograma_sedeuniversidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionacademica',
            name='codigo_estudiante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
