# Generated by Django 4.2.1 on 2023-06-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0005_remove_pertenenciagrupopoblacional_personas_and_more'),
        ('app_informacion_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciongeneral',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_registro.persona'),
        ),
    ]
