# Generated by Django 4.2.1 on 2023-06-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0002_alter_informaciongeneral_id_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionOcupacion',
            fields=[
                ('id_informacion_ocupacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_informacion_ocupacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='informacion_ocupaciones',
            field=models.ManyToManyField(max_length=200, to='app_informacion_general.informacionocupacion'),
        ),
    ]
