# Generated by Django 4.2.1 on 2023-06-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0003_informacionocupacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformacionOcupacion',
            new_name='OcupacionActual',
        ),
        migrations.RenameField(
            model_name='informaciongeneral',
            old_name='informacion_ocupaciones',
            new_name='ocupaciones_actuales',
        ),
        migrations.RenameField(
            model_name='ocupacionactual',
            old_name='nombre_informacion_ocupacion',
            new_name='nombre_ocupacion_actual',
        ),
    ]
