# Generated by Django 4.2.1 on 2023-06-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0005_rename_id_informacion_ocupacion_ocupacionactual_id_ocupacion_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='nombre_persona_confianza',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='telefono_persona_confianza',
        ),
    ]
