# Generated by Django 4.2.1 on 2023-06-09 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0006_remove_informaciongeneral_nombre_persona_confianza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTiempoLibre',
            fields=[
                ('id_actividad_tiempo_libre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad_tiempo_libre', models.CharField(max_length=200)),
                ('observacion_actividad_tiempo_libre', models.TextField(blank=True, null=True)),
                ('id_informacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_informacion_general.informaciongeneral')),
            ],
        ),
    ]
