# Generated by Django 4.2.1 on 2023-06-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0007_actividadtiempolibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadtiempolibre',
            name='id_informacion_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_tiempo_libre', to='app_informacion_general.informaciongeneral'),
        ),
        migrations.AlterField(
            model_name='actividadtiempolibre',
            name='observacion_actividad_tiempo_libre',
            field=models.TextField(blank=True, default='Sin observación'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='ocupaciones_actuales',
            field=models.ManyToManyField(max_length=200, related_name='informaciones_generales', to='app_informacion_general.ocupacionactual'),
        ),
    ]
