# Generated by Django 4.2.1 on 2023-06-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0008_alter_actividadtiempolibre_id_informacion_general_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actividadtiempolibre',
            table='Informacion_general_actividad_tiempo_libre',
        ),
        migrations.AlterModelTable(
            name='ocupacionactual',
            table='Informacion_general_ocupacion_actual',
        ),
    ]
