# Generated by Django 4.2.1 on 2023-06-09 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0009_alter_actividadtiempolibre_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteIngresos',
            fields=[
                ('id_fuente_ingresos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fuente_ingresos', models.CharField(max_length=200)),
                ('observacion_fuente_ingresos', models.TextField(blank=True, default='Sin Observación')),
                ('id_informacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_ingresos', to='app_informacion_general.informaciongeneral')),
            ],
        ),
    ]
