# Generated by Django 4.2.1 on 2023-06-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0010_fuenteingresos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadtiempolibre',
            name='id_informacion_general',
            field=models.ForeignKey(blank=True, default='2', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_tiempo_libre', to='app_informacion_general.informaciongeneral'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuenteingresos',
            name='id_informacion_general',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_de_ingresos', to='app_informacion_general.informaciongeneral'),
        ),
        migrations.AlterModelTable(
            name='fuenteingresos',
            table='Informacion_general_fuente_ingresos',
        ),
        migrations.CreateModel(
            name='ConvivenciaVivienda',
            fields=[
                ('id_convivencia_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_convivencia_vivienda', models.CharField(max_length=200)),
                ('observacion_convivencia_vivienda', models.TextField(blank=True, null=True)),
                ('id_informacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivencias_en_vivienda', to='app_informacion_general.informaciongeneral')),
            ],
            options={
                'db_table': 'Informacion_general_convivencia_familiar',
            },
        ),
    ]
