# Generated by Django 4.2.1 on 2023-06-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0011_alter_actividadtiempolibre_id_informacion_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convivenciavivienda',
            name='id_informacion_general',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='convivencias_en_vivienda', to='app_informacion_general.informaciongeneral'),
        ),
        migrations.AlterField(
            model_name='convivenciavivienda',
            name='observacion_convivencia_vivienda',
            field=models.TextField(blank=True, default='Sin observacion'),
        ),
        migrations.AlterModelTable(
            name='convivenciavivienda',
            table='Informacion_general_convivencia_vivienda',
        ),
    ]
