# Generated by Django 4.2.1 on 2023-06-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0013_redapoyo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorRiesgo',
            fields=[
                ('id_factor_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_factor_riesgo', models.CharField(max_length=200)),
                ('observacion_factor_riesgo', models.TextField(blank=True, default='Sin observacion')),
                ('id_informacion_general', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='factores_de_riesgo', to='app_informacion_general.informaciongeneral')),
            ],
            options={
                'db_table': 'Informacion_general_factor_riesgo',
            },
        ),
    ]
