# Generated by Django 4.2.1 on 2023-06-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0014_factorriesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_horario',
            field=models.TextField(default='Sin observación'),
        ),
        migrations.CreateModel(
            name='EncuentroDiaHora',
            fields=[
                ('id_encuentro_dia_hora', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora', models.TimeField()),
                ('id_informacion_general', models.ManyToManyField(blank=True, related_name='encuentro_dias_horas', to='app_informacion_general.informaciongeneral')),
            ],
            options={
                'db_table': 'Informacion_general_encuentro_dia_hora',
            },
        ),
    ]
