# Generated by Django 4.2.1 on 2024-05-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0016_alter_informaciongeneral_id_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalQueBrindoAtencion',
            fields=[
                ('id_profesion_que_brindo_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_profesional_que_brindo_atencion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Informacion_general_profesional_que_brindo_atencion',
            },
        ),
        migrations.RenameField(
            model_name='informaciongeneral',
            old_name='relacion_familiar',
            new_name='calificacion_relacion_familiar',
        ),
        migrations.RenameField(
            model_name='informaciongeneral',
            old_name='encuentro_inicial',
            new_name='decision_encuentro_inicial_con_profesional',
        ),
        migrations.RenameField(
            model_name='informaciongeneral',
            old_name='observacion_general_relacion_familiar',
            new_name='observacion_general_relacion_convivencia_familiar',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='observacion_tipo_acompanamiento_recibido',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='tipo_acompanamiento_recibido',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='tipo_profesional_acompanamiento_recibido',
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='nombre_eps',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='regimen_eps',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='tiene_eps',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='comentarios_o_sugerencias_de_usuario',
            field=models.TextField(default='N/A'),
        ),
        migrations.CreateModel(
            name='AcompanamientoRecibido',
            fields=[
                ('id_acompanamiento_recibido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_acompanamiento_recibido', models.CharField(max_length=200)),
                ('observacion_acompanamiento_recibido', models.TextField(default='N/A')),
                ('id_informacion_general', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acompanamientos_recibido', to='app_informacion_general.informaciongeneral')),
            ],
            options={
                'db_table': 'Informacion_general_acompanamiento_recibido',
            },
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='profesionales_que_brindo_atencion',
            field=models.ManyToManyField(max_length=200, related_name='informaciones_generales', to='app_informacion_general.profesionalquebrindoatencion'),
        ),
    ]
