# Generated by Django 4.2.1 on 2024-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0018_rename_observacion_general_relacion_convivencia_familiar_informaciongeneral_observacion_general_rela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciongeneral',
            name='tiene_eps',
            field=models.CharField(blank=True, default='N/A', max_length=30),
        ),
    ]
