# Generated by Django 4.2.1 on 2024-06-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0020_alter_acompanamientorecibido_id_informacion_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanamientorecibido',
            name='id_informacion_general',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acompanamientos_recibido', to='app_informacion_general.informaciongeneral'),
        ),
    ]
