# Generated by Django 4.2.13 on 2024-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0021_alter_acompanamientorecibido_id_informacion_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanamientorecibido',
            name='nombre_acompanamiento_recibido',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='acompanamientorecibido',
            name='observacion_acompanamiento_recibido',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='actividadtiempolibre',
            name='nombre_actividad_tiempo_libre',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='convivenciavivienda',
            name='nombre_convivencia_vivienda',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='encuentrodiahora',
            name='dia',
            field=models.CharField(blank=True, default='Sin observación', max_length=30),
        ),
        migrations.AlterField(
            model_name='encuentrodiahora',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factorriesgo',
            name='nombre_factor_riesgo',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='fuenteingresos',
            name='nombre_fuente_ingresos',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='actividades_especificas_tiempo_libre',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='calificacion_relacion_familiar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='comentarios_o_sugerencias_de_usuario',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='creencia_religiosa',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='decision_encuentro_inicial_con_profesional',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='dedicacion_externa',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_general_actividades_especificas_tiempo_libre',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_general_factores_de_riesgo',
            field=models.TextField(blank=True, default='Sin observación'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_general_fuente_de_ingresos',
            field=models.TextField(blank=True, default='Sin observación'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_general_redes_de_apoyo',
            field=models.TextField(blank=True, default='Sin observación'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_general_relacion_convivencia_vivienda',
            field=models.TextField(blank=True, default='Sin observación'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_horario',
            field=models.TextField(blank=True, default='Sin observación'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='ocupaciones_actuales',
            field=models.ManyToManyField(blank=True, max_length=200, related_name='informaciones_generales', to='app_informacion_general.ocupacionactual'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='origen_descubrimiento_campus_diverso',
            field=models.CharField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='profesionales_que_brindo_atencion',
            field=models.ManyToManyField(blank=True, max_length=200, related_name='informaciones_generales', to='app_informacion_general.profesionalquebrindoatencion'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='tipo_entidad_acompanamiento_recibido',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='redapoyo',
            name='nombre_red_apoyo',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
    ]
