# Generated by Django 5.0.7 on 2024-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0022_alter_acompanamientorecibido_nombre_acompanamiento_recibido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesTiempoLibre',
            fields=[
                ('id_actividad_de_tiempo_libre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad_de_tiempo_libre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FactoresRiesgo',
            fields=[
                ('id_factor_de_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_factor_de_riesgo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FuentesIngreso',
            fields=[
                ('id_fuente_de_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fuente_de_ingreso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RedesApoyo',
            fields=[
                ('id_red_de_apoyo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_red_de_apoyo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='actividadtiempolibre',
            name='id_informacion_general',
        ),
        migrations.RemoveField(
            model_name='convivenciavivienda',
            name='id_informacion_general',
        ),
        migrations.RemoveField(
            model_name='factorriesgo',
            name='id_informacion_general',
        ),
        migrations.RemoveField(
            model_name='fuenteingresos',
            name='id_informacion_general',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='ocupaciones_actuales',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='profesionales_que_brindo_atencion',
        ),
        migrations.RemoveField(
            model_name='redapoyo',
            name='id_informacion_general',
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='Ocupaciones_actules',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='acompanamiento_que_recibio',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='profesionales_que_brindaron_atencion',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='tiene_eps',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='actividades_tiempo_libre',
            field=models.ManyToManyField(blank=True, max_length=500, to='app_informacion_general.actividadestiempolibre'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='factores_riesgos',
            field=models.ManyToManyField(blank=True, max_length=500, to='app_informacion_general.factoresriesgo'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='fuentes_ingresos',
            field=models.ManyToManyField(blank=True, max_length=500, to='app_informacion_general.fuentesingreso'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='redes_apoyo',
            field=models.ManyToManyField(blank=True, max_length=500, to='app_informacion_general.redesapoyo'),
        ),
        migrations.DeleteModel(
            name='AcompanamientoRecibido',
        ),
        migrations.DeleteModel(
            name='ActividadTiempoLibre',
        ),
        migrations.DeleteModel(
            name='ConvivenciaVivienda',
        ),
        migrations.DeleteModel(
            name='FactorRiesgo',
        ),
        migrations.DeleteModel(
            name='FuenteIngresos',
        ),
        migrations.DeleteModel(
            name='OcupacionActual',
        ),
        migrations.DeleteModel(
            name='ProfesionalQueBrindoAtencion',
        ),
        migrations.DeleteModel(
            name='RedApoyo',
        ),
    ]
