# Generated by Django 5.0.7 on 2024-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0023_actividadestiempolibre_factoresriesgo_fuentesingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_general_actividades_especificas_tiempo_libre',
            field=models.TextField(blank=True, default='SIn observación'),
        ),
    ]
