# Generated by Django 5.0.7 on 2025-03-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0024_alter_informaciongeneral_observacion_general_actividades_especificas_tiempo_libre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='calificacion_acompanamiento_recibido',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='dedicacion_externa',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='motivo_calificacion_acompanamiento',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='profesionales_que_brindaron_atencion',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='tipo_entidad_acompanamiento_recibido',
        ),
    ]
