# Generated by Django 5.0.7 on 2025-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_informacion_general', '0025_remove_informaciongeneral_calificacion_acompanamiento_recibido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionEncuentroInicial',
            fields=[
                ('id_decision_encuentro_inicial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_decision_encuentro_inicial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegimenEps',
            fields=[
                ('id_regimen_eps', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_regimen_eps', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='decision_encuentro_inicial_con_profesional',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='regimen_eps',
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='tiene_eps',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='decision_encuentro_inicial',
            field=models.ManyToManyField(blank=True, max_length=500, to='app_informacion_general.decisionencuentroinicial'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='regimen_eps',
            field=models.ManyToManyField(blank=True, max_length=500, to='app_informacion_general.regimeneps'),
        ),
    ]
