# Generated by Django 4.1.1 on 2023-01-04 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modulo_usuario_rol", "0020_delete_instancia_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="seguimiento_individual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("lugar", models.CharField(max_length=100)),
                ("hora_inicio", models.TimeField()),
                ("hora_finalización", models.TimeField()),
                ("objetivos", models.CharField(max_length=1500, null=True)),
                ("individual", models.CharField(max_length=1500, null=True)),
                ("riesgo_individual", models.IntegerField()),
                ("autoconocimiento", models.BooleanField()),
                ("rasgos_de_personalidad", models.BooleanField()),
                ("identificación", models.BooleanField()),
                ("red_de_apoyo", models.BooleanField()),
                ("proyecto_de_vida", models.BooleanField()),
                ("salud", models.BooleanField()),
                ("aspectos_motivacionales", models.BooleanField()),
                ("historia_de_vida", models.BooleanField()),
                ("relación_eriótico_afectivas", models.BooleanField()),
                ("diversidad_sexual", models.BooleanField()),
                ("familiar", models.CharField(max_length=1500, null=True)),
                ("riesgo_familiar", models.IntegerField()),
                ("dinamica_familiar", models.BooleanField()),
                ("academico", models.CharField(max_length=1500, null=True)),
                ("riesgo_academico", models.IntegerField()),
                ("desempeño_académico", models.BooleanField()),
                ("elección_vocacional", models.BooleanField()),
                ("manejo_del_tiempo", models.BooleanField()),
                ("economico", models.CharField(max_length=1500, null=True)),
                ("riesgo_economico", models.IntegerField()),
                ("apoyos_económicos_institucionales", models.BooleanField()),
                ("manejo_finanzas", models.BooleanField()),
                ("apoyo_económico_familiar", models.BooleanField()),
                ("situación_laboral_ocupacional", models.BooleanField()),
                (
                    "vida_universitaria_ciudad",
                    models.CharField(max_length=1500, null=True),
                ),
                ("riesgo_vida_universitaria_ciudad", models.IntegerField()),
                ("motivación_compañamiento", models.BooleanField()),
                ("referencia_geográfica", models.BooleanField()),
                ("adaptación_ciudad_Universidad", models.BooleanField()),
                ("oferta_servicios", models.BooleanField()),
                ("vivienda", models.BooleanField()),
                (
                    "vinculación_grupos_actividades_extracurriculares",
                    models.BooleanField(),
                ),
                ("acciones", models.CharField(max_length=1500)),
                ("observaciones", models.CharField(max_length=1500, null=True)),
                ("revisado_profesional", models.BooleanField()),
                ("revisado_practicante", models.BooleanField()),
                ("primer_acercamiento", models.BooleanField()),
                ("cierre", models.BooleanField()),
                ("creacion", models.DateTimeField(auto_now_add=True)),
                ("modificacion", models.DateTimeField(auto_now=True)),
                (
                    "id_creador",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_creador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_estudiante",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modulo_usuario_rol.estudiante",
                    ),
                ),
                (
                    "id_modificador",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_modificador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_monitor",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_monitor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_practicante",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_practicante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_profesional",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_profesional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "seguimiento_individual",},
        ),
        migrations.CreateModel(
            name="inasistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("observaciones", models.CharField(max_length=1500)),
                ("revisado_profesional", models.BooleanField()),
                ("revisado_practicante", models.BooleanField()),
                ("creacion", models.DateTimeField(auto_now_add=True)),
                ("modificacion", models.DateTimeField(auto_now=True)),
                (
                    "id_creador",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_estudiante",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modulo_usuario_rol.estudiante",
                    ),
                ),
                (
                    "id_modificador",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modificador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_monitor",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_practicante",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practicante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_profesional",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profesional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "inasistencia",},
        ),
    ]
