# Generated by Django 4.1.1 on 2023-01-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_seguimiento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inasistencia",
            name="modificacion",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="seguimiento_individual", name="fecha", field=models.DateField(),
        ),
    ]
