# Generated by Django 4.1.1 on 2023-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_seguimiento", "0002_alter_inasistencia_modificacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inasistencia", name="fecha", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="inasistencia",
            name="modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
