# Generated by Django 4.1.1 on 2023-10-27 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0002_estudiante_es_discapacidad'),
        ('modulo_seguimiento', '0002_alter_inasistencia_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='riesgo_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_individual', models.IntegerField(null=True)),
                ('riesgo_familiar', models.IntegerField(null=True)),
                ('riesgo_academico', models.IntegerField(null=True)),
                ('riesgo_economico', models.IntegerField(null=True)),
                ('riesgo_vida_universitaria_ciudad', models.IntegerField(null=True)),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'riesgo_individual',
            },
        ),
    ]
