# Generated by Django 4.1.1 on 2023-01-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_seguimiento", "0003_alter_inasistencia_fecha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inasistencia",
            name="revisado_practicante",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inasistencia",
            name="revisado_profesional",
            field=models.BooleanField(default=False),
        ),
    ]
