# Generated by Django 4.1.1 on 2023-10-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_seguimiento', '0003_riesgo_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgo_individual',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
