# Generated by Django 4.1 on 2024-07-18 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_instancia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("modulo_seguimiento", "0004_riesgo_individual_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="riesgo_individual",
            name="id_semestre",
            field=models.ForeignKey(
                default=40,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_semestre_in_riesgo_individual",
                to="modulo_instancia.semestre",
            ),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_actividades_grupales",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_desa_humano",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_dir_programa",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_grupo_uni",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_matricula_financiera",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_monitoria_aca",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_practicante_se",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_prof_se",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_proyect_uni",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_regis_academico",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_rem_externa",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="asist_servi_salud",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="historial_ficha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "id_ficha",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_ficha_in_historial_ficha",
                        to="modulo_seguimiento.seguimiento_individual",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_user_in_historial_ficha",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "historial_ficha",},
        ),
    ]
