# Generated by Django 4.1 on 2024-07-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_seguimiento", "0005_riesgo_individual_id_semestre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial_ficha",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
