# Generated by Django 4.1.1 on 2023-01-04 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("modulo_seguimiento", "0005_alter_seguimiento_individual_cierre_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="inasistencia", name="id_monitor",),
        migrations.RemoveField(model_name="inasistencia", name="id_practicante",),
        migrations.RemoveField(model_name="inasistencia", name="id_profesional",),
        migrations.RemoveField(model_name="seguimiento_individual", name="id_monitor",),
        migrations.RemoveField(
            model_name="seguimiento_individual", name="id_practicante",
        ),
        migrations.RemoveField(
            model_name="seguimiento_individual", name="id_profesional",
        ),
        migrations.AlterField(
            model_name="inasistencia",
            name="id_creador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_creador_inasistencia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inasistencia",
            name="id_modificador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_modificador_inasistencia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seguimiento_individual",
            name="id_creador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_creador_seguimiento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seguimiento_individual",
            name="id_modificador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_modificador_seguimiento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
