# Generated by Django 4.1.1 on 2023-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_seguimiento", "0006_remove_inasistencia_id_monitor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seguimiento_individual",
            name="riesgo_academico",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="seguimiento_individual",
            name="riesgo_economico",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="seguimiento_individual",
            name="riesgo_familiar",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="seguimiento_individual",
            name="riesgo_individual",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="seguimiento_individual",
            name="riesgo_vida_universitaria_ciudad",
            field=models.IntegerField(null=True),
        ),
    ]
