# Generated by Django 5.2.4 on 2025-08-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_seguimiento', '0007_seguimiento_individual_objetivos2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento_individual',
            name='autogestion_academica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='autonomia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='integracion_a_la_cultura_universitaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='movilidad_y_transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='red_de_apoyo_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='relaciones_familiares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='rol_del_estudiante_en_la_familia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='uso_de_los_servicios_universitarios',
            field=models.BooleanField(default=False),
        ),
    ]
