# Generated by Django 4.1.1 on 2023-01-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modulo_seguimiento",
            "0007_alter_seguimiento_individual_riesgo_academico_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="seguimiento_individual", name="acciones",),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="Ninguna_acción_realizada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="apoyo_académico",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="reconocimiento_ciudad_U",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_actividades_grupales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_desarrollo_humano_promoción_SE",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_directores_programa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_externa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_grupos_universidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_matrícula_financiera",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_monitorías_académicas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_profesional_SE",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_proyectos_Universidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_racticante_SE",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_registro_académico",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="rem_servicio_salud",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seguimiento_individual",
            name="taller_par_par",
            field=models.BooleanField(default=False),
        ),
    ]
