# Generated by Django 5.2.4 on 2026-05-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_seguimiento', '0008_seguimiento_individual_autogestion_academica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento_individual',
            name='escucha_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='rem_OITEL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento_individual',
            name='rem_rep_estudiantiles',
            field=models.BooleanField(default=False),
        ),
    ]
