# Generated by Django 4.1.1 on 2023-10-05 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_divipola", models.IntegerField()),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={"db_table": "departamento",},
        ),
        migrations.CreateModel(
            name="municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_divipola", models.BigIntegerField()),
                ("nombre", models.CharField(max_length=50)),
                (
                    "cod_dep",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modulo_geografico.departamento",
                    ),
                ),
            ],
            options={"db_table": "municipio",},
        ),
        migrations.CreateModel(
            name="barrio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_barrio", models.BigIntegerField()),
                (
                    "estrato",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(10)]
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "cod_municipio",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modulo_geografico.municipio",
                    ),
                ),
            ],
            options={"db_table": "barrio",},
        ),
    ]
