# Generated by Django 4.2.3 on 2023-07-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_geografico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
