# Generated by Django 4.2.6 on 2023-10-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuario_rol', '0002_estudiante_es_discapacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='dis_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_discapacidad', models.CharField(choices=[('FIS', 'Física'), ('MUL', 'Múltiple'), ('PSI', 'Psicosocial'), ('SEN', 'Sensorial'), ('COG', 'Cognitiva')], default='COG', max_length=3)),
                ('adquisicion', models.CharField(choices=[('VIOLENCIA', 'Víctima de violencias'), ('HEREDITARIO', 'Enfermedad de orden hereditario'), ('GENETICO', 'Enfermedad de orden genético'), ('GENERAL', 'Enfermedad general'), ('OTRA', 'Otra')], default='OTRA', max_length=12)),
            ],
            options={
                'db_table': 'dis_estudiante',
            },
        ),
        migrations.CreateModel(
            name='dis_estudiante_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_discapacidad_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='modulo_discapacidad.dis_estudiante')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'dis_estudiante__estudiante',
            },
        ),
    ]
