# Generated by Django 4.2.6 on 2023-10-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0002_estudiante_es_discapacidad'),
        ('modulo_discapacidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discapacidad_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_discapacidad', models.CharField(choices=[('FIS', 'Física'), ('MUL', 'Múltiple'), ('PSI', 'Psicosocial'), ('SEN', 'Sensorial'), ('COG', 'Cognitiva')], default='COG', max_length=3)),
                ('adquisicion', models.CharField(choices=[('VIOLENCIA', 'Víctima de violencias'), ('HEREDITARIO', 'Enfermedad de orden hereditario'), ('GENETICO', 'Enfermedad de orden genético'), ('GENERAL', 'Enfermedad general'), ('OTRA', 'Otra')], default='OTRA', max_length=12)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discapacidad', to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'discapacidad_estudiante',
            },
        ),
        migrations.RemoveField(
            model_name='dis_estudiante_estudiante',
            name='id_discapacidad_estudiante',
        ),
        migrations.RemoveField(
            model_name='dis_estudiante_estudiante',
            name='id_estudiante',
        ),
        migrations.DeleteModel(
            name='dis_estudiante',
        ),
        migrations.DeleteModel(
            name='dis_estudiante_estudiante',
        ),
    ]
