# Generated by Django 4.1 on 2024-08-12 21:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("modulo_discapacidad", "0004_accesibilidad_comunicacional_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="percepcion_discapacidad", name="id_consideracion_discapacidad",
        ),
        migrations.RemoveField(
            model_name="percepcion_discapacidad", name="id_dificultad_permanente",
        ),
        migrations.RemoveField(
            model_name="percepcion_discapacidad", name="id_experimenta_dificultad",
        ),
        migrations.RemoveField(
            model_name="percepcion_discapacidad", name="id_factores",
        ),
        migrations.RemoveField(
            model_name="percepcion_discapacidad", name="id_personas_apoyo",
        ),
        migrations.RemoveField(
            model_name="percepcion_discapacidad", name="id_posibilidad_actividades",
        ),
        migrations.RemoveField(
            model_name="percepcion_discapacidad", name="id_salud_tener_cuenta",
        ),
        migrations.AddField(
            model_name="caracterizacion",
            name="fecha",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="caracterizacion",
            name="id_creador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_user_in_caracterizacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caracterizacion",
            name="lugar",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="act_otras_per",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="actitudes_negativas_personas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="adquisicion",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="alimentos_cafeteria",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="alimentos_cafeteria_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="amigo_apoyo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="apoyo_inst",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="asambleas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="asambleas_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="asearse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="asearse_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="audicion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="audicion_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ausencia_ayuda_tec",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ausencia_espacios_fisicos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ausencia_personas_apoyo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ausencia_servicios_discapacidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="cerebro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="cerebro_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="certificado_invalidez",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="clases_magistrales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="clases_magistrales_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="cognicion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="cognicion_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="compren_oral",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="compren_oral_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="conciertos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="conciertos_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="condicion_discapacidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="condicion_psicoemocional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="conferencias",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="conferencias_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="considera_discapacidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="consideracion",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="consumier_alimen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="consumier_alimen_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="contexto_universitario",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="copia_dictado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="copia_dictado_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="cuenta_con_diagnostico",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="curausencia_materiales_impresossos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="cursos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="cursos_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="deglucion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="deglucion_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="desplazarse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="desplazarse_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="documento_soporte",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="elaborar_ideas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="elaborar_ideas_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="escritos_impresos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="escritos_impresos_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="escuchar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="escuchar_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="estado_socio_emocional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="estado_socio_emocional_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="evacuar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="evacuar_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="expre_oral",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="expre_oral_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="familia_apoyo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="imagenes_pantalla",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="imagenes_pantalla_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="interactuar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="interactuar_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="laboratorios",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="laboratorios_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="manipular_obj",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="manipular_obj_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="manos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="manos_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="mant_sentado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="mant_sentado_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="manuales_escritos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="manuales_escritos_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="movilizacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="movilizacion_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="movimiento_cuerpo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="movimiento_cuerpo_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="nombre_institucion",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ocio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ocio_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="oidos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="oidos_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ojos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="ojos_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otra_psicoemocional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otra_psicoemocional_texto",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otra_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otro_apoyo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otro_desplazar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otro_texto",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otros_factores",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="otros_factores_texto",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="pareja_apoyo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="participa_org",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="piel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="piel_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="piernas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="piernas_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="practica_deportiva",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="practica_deportiva_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="privado_desplazar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="propio_desplazar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="publico_desplazar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="redactar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="redactar_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="rel_interpersonales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="rel_interpersonales_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="relaciones_sexuales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="relaciones_sexuales_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="salud_apoyo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="secuencias_numericas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="secuencias_numericas_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="servicios_salud",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="servicios_salud_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_cardio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_cardio_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_digestivo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_genital",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_genital_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_gigestivo_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_nervioso",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="sistema_nervioso_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="talleres",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="talleres_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="textos_pantalla",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="textos_pantalla_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="tipo_apoyo",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="tipo_diagnostico",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="tramites",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="tramites_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="transcripcion_textos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="transcripcion_textos_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="vestirse_desves",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="vestirse_desves_numero",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="vision",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="vision_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="vocales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="vocales_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="voz_y_habla",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="percepcion_discapacidad",
            name="voz_y_habla_texto",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user_extended_disc",
            name="celular",
            field=models.CharField(
                default=None,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Por favor ingresa un teléfono o celular valido",
                        regex="^[()\\-0-9\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user_extended_disc",
            name="profesion",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(name="consideracion_discapacidad_pd",),
        migrations.DeleteModel(name="dificultad_permanente_pd",),
        migrations.DeleteModel(name="experimenta_dificultad_pd",),
        migrations.DeleteModel(name="factores_pd",),
        migrations.DeleteModel(name="personas_apoyo_pd",),
        migrations.DeleteModel(name="posibilidad_actividades_pd",),
        migrations.DeleteModel(name="salud_tener_cuenta_pd",),
    ]
