# Generated by Django 4.1 on 2024-08-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "modulo_discapacidad",
            "0005_remove_percepcion_discapacidad_id_consideracion_discapacidad_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="percepcion_discapacidad",
            old_name="curausencia_materiales_impresossos",
            new_name="ausencia_materiales_impresos",
        ),
        migrations.RenameField(
            model_name="percepcion_discapacidad",
            old_name="sistema_gigestivo_texto",
            new_name="sistema_digestivo_texto",
        ),
    ]
