# Generated by Django 5.1.1 on 2024-09-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_discapacidad', '0007_datos_entrevistado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_economicos',
            name='actualmente_vive_estado',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='actualmente_vive_parentezco',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='expectativas_carrera',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='expectativas_grado',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='hijos_numero',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='labor_madre',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='labor_padre',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='motivo_ingreso',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='otro_familiar_actividad_economica',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='otro_familiar_labor_desempena',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='otro_familiar_nivel_educativo',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='otro_familiar_situacion_economica',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='permanencia_ingresos_familiares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='permanencia_ingresos_otros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='permanencia_ingresos_otros_texto',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='permanencia_ingresos_propios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='requiere_materiales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='tiene_hijos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='transporte_otro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='transporte_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='transporte_propio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='transporte_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='valor_materiales',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='valor_sostenimiento',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datos_economicos',
            name='valor_transporte',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
