# Generated by Django 5.1.1 on 2024-09-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_discapacidad', '0008_datos_economicos_actualmente_vive_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_economicos',
            name='transporte_otro_data',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
