# Generated by Django 5.1.1 on 2024-09-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_discapacidad', '0009_datos_economicos_transporte_otro_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso_servi_salud',
            name='salud_pre_nombre_institucion',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acceso_servi_salud',
            name='salud_prepagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceso_servi_salud',
            name='servicio_complementario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceso_servi_salud',
            name='servicio_complementario_nombre',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acceso_servi_salud',
            name='servicio_estudiantil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceso_servi_salud',
            name='servicio_estudiantil_nombre',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acceso_servi_salud',
            name='servicio_salud',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
