# Generated by Django 5.1.1 on 2024-09-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_discapacidad', '0010_acceso_servi_salud_salud_pre_nombre_institucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_academicos',
            name='edu_media_dificultad_apoyo',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='edu_media_nombre_institucion',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='edu_media_tipo_institucion',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='edu_media_titulo_obtenido',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='edu_superior_dificultad_apoyo',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='edu_superior_tipo_institucion',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='observaciones_adicionales',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='otros_programas_academicos',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='periodo_ingreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
