# Generated by Django 5.1.1 on 2024-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_discapacidad', '0011_datos_academicos_edu_media_dificultad_apoyo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percepcion_discapacidad',
            old_name='otra',
            new_name='otra_dif_permanente',
        ),
        migrations.RenameField(
            model_name='percepcion_discapacidad',
            old_name='otra_texto',
            new_name='otra_dif_permanente_texto',
        ),
        migrations.AddField(
            model_name='percepcion_discapacidad',
            name='otra_nec_diferente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='percepcion_discapacidad',
            name='otra_nec_diferente_texto',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='percepcion_discapacidad',
            name='otra_organos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='percepcion_discapacidad',
            name='otra_organos_texto',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
