# Generated by Django 5.1.1 on 2024-09-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_discapacidad', '0012_rename_otra_percepcion_discapacidad_otra_dif_permanente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='jornada_caracterizacion',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
