# Generated by Django 4.2.1 on 2024-06-22 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_registro', '0007_remove_persona_incluir_correo_en_respuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='app_registro.persona')),
                ('profesionales', models.ManyToManyField(related_name='seguimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Seguimiento',
            },
        ),
    ]
