# Generated by Django 4.2.13 on 2024-06-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='profesionales',
        ),
    ]
