# Generated by Django 4.2.13 on 2024-07-16 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_seguimiento', '0002_remove_seguimiento_profesionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_profesional', models.TextField()),
                ('ocupacion_profesional', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='id_creador_campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_creador_campus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='profesional',
            field=models.ManyToManyField(blank=True, to='app_seguimiento.profesional'),
        ),
    ]
