# Generated by Django 4.2.13 on 2024-07-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento', '0003_profesional_seguimiento_id_creador_campus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='ocupacion_profesional',
        ),
    ]
