# Generated by Django 5.0.7 on 2024-07-17 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento', '0004_remove_profesional_ocupacion_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observacion',
            field=models.TextField(blank=True, default='Sin observación'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='profesional',
            field=models.ManyToManyField(blank=True, default='N/A', to='app_seguimiento.profesional'),
        ),
    ]
