# Generated by Django 5.0.7 on 2024-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento', '0005_alter_seguimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='cargo_profesional',
            field=models.CharField(blank=True, default='sin cargo', max_length=100),
        ),
    ]
