# Generated by Django 4.2.4 on 2023-08-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuario_rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=150)),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_estudiante_in_retiro', to='modulo_usuario_rol.estudiante')),
                ('id_motivo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_motivo_in_retiro', to='modulo_carga_masiva.motivo')),
            ],
        ),
    ]
