# Generated by Django 4.1 on 2024-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_carga_masiva", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="motivo",
            name="motivo_activo",
            field=models.BooleanField(default=True),
        ),
    ]
