# Generated by Django 4.0 on 2022-06-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuario_rol', '0004_permiso_rol_usuario_rol_rol_permiso_estudiante'),
        ('modulo_instancia', '0001_initial'),
        ('modulo_asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='id_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_semestre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.usuario'),
        ),
    ]
