# Generated by Django 4.1.1 on 2022-11-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_asignacion", "0004_asignacion_ue_asignacion_uu_delete_asignacion"),
    ]

    operations = [
        migrations.AlterModelTable(name="asignacion_ue", table="asignacion",),
        migrations.DeleteModel(name="asignacion_UU",),
    ]
