# Generated by Django 4.1.1 on 2022-11-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_asignacion", "0005_alter_asignacion_ue_table_delete_asignacion_uu"),
    ]

    operations = [
        migrations.DeleteModel(name="asignacion_UE",),
    ]
