# Generated by Django 4.2.1 on 2023-06-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pertenenciagrupopoblacional',
            name='personas',
            field=models.ManyToManyField(blank=True, to='app_registro.persona'),
        ),
    ]
