# Generated by Django 4.2.1 on 2023-06-02 23:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0002_alter_persona_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pertenencia_grupo_poblacional',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
