# Generated by Django 4.2.1 on 2024-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0006_persona_ciudad_nacimiento_persona_ciudad_residencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='incluir_correo_en_respuesta',
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, default='Email no registrado', max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='barrio_residencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion_residencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_persona_de_confianza',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='relacion_persona_de_confianza',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono_persona_de_confianza',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='zona_residencial',
            field=models.CharField(max_length=500),
        ),
    ]
