# Generated by Django 4.2.13 on 2024-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0007_remove_persona_incluir_correo_en_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='barrio_residencia',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad_nacimiento',
            field=models.CharField(blank=True, default='Ciudad no especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad_residencia',
            field=models.CharField(blank=True, default='Ciudad no especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comuna_barrio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='corregimiento_nacimiento',
            field=models.CharField(blank=True, default='Corregimiento no especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='corregimiento_residencia',
            field=models.CharField(blank=True, default='Corregimiento no especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion_residencia',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identidad_etnico_racial',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='persona',
            name='municipio_nacimiento',
            field=models.CharField(blank=True, default='Municipio no especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='municipio_residencia',
            field=models.CharField(blank=True, default='Municipio no especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_persona_de_confianza',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais_nacimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pertenencia_grupo_poblacional',
            field=models.ManyToManyField(blank=True, max_length=300, related_name='personas', to='app_registro.pertenenciagrupopoblacional'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='relacion_persona_de_confianza',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono_persona_de_confianza',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='zona_residencial',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
