# Generated by Django 4.2.13 on 2024-07-08 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0008_alter_persona_barrio_residencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='barrio_residencia',
            field=models.CharField(blank=True, default='Barrio de residencia no registrado', max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comuna_barrio',
            field=models.CharField(blank=True, default='Comuna/barrio no registrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='departamento_nacimiento',
            field=models.CharField(blank=True, default='No especifica Departamento de nacimiento', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion_residencia',
            field=models.CharField(blank=True, default='Direccion de residencia no registrado', max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, default='Estado civil no registrado', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estrato_socioeconomico',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identidad_etnico_racial',
            field=models.CharField(blank=True, default='Identidad etnico racial no registrado', max_length=70),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_identitario',
            field=models.CharField(blank=True, default='Nomber identitario no registrado', max_length=150),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_persona_de_confianza',
            field=models.CharField(blank=True, default='Nombre de persona de confianza no registrado', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_y_apellido',
            field=models.CharField(blank=True, default='No especifica nombre y/o apellido', max_length=150),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais_nacimiento',
            field=models.CharField(blank=True, default='Pais de nacimiento no registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='relacion_persona_de_confianza',
            field=models.CharField(blank=True, default='Relacion con persona de confianza no registrado', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, default='Telefono no registrado', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono_persona_de_confianza',
            field=models.CharField(blank=True, default='Telefono de persona de confianza no registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(blank=True, default='Tipo de documento no especificado', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='zona_residencial',
            field=models.CharField(blank=True, default='Zona de residencia no registrado', max_length=500),
        ),
    ]
