# Generated by Django 4.2.13 on 2024-07-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0010_alter_persona_municipio_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='comuna_barrio',
            field=models.CharField(blank=True, default='Comuna/barrio no registrado', max_length=70),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, default='Email no registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, default='Estado civil no registrado', max_length=70),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, default='Telefono no registrado', max_length=70),
        ),
    ]
