# Generated by Django 5.0.7 on 2024-08-08 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0011_alter_persona_comuna_barrio_alter_persona_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='recaptchaToken',
            field=models.CharField(default=django.utils.timezone.now, max_length=450),
            preserve_default=False,
        ),
    ]
