# Generated by Django 5.0.7 on 2024-08-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0012_persona_recaptchatoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_creacion_usuario',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='revision_usiario',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
