# Generated by Django 5.0.7 on 2024-08-08 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0013_persona_fecha_creacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_creacion_usuario',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
