# Generated by Django 5.0.7 on 2024-08-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0014_alter_persona_fecha_creacion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Tipo_documento',
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.ManyToManyField(blank=True, max_length=300, to='app_registro.tipodocumento'),
        ),
    ]
