# Generated by Django 5.0.7 on 2025-03-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0015_tipodocumento_remove_persona_tipo_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_civil', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Estado_civil',
            },
        ),
        migrations.CreateModel(
            name='IdentidadEtnicoRacial',
            fields=[
                ('id_identidad_etnico_racial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_identidad_etnico_racial', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Identidad_etnico_racial',
            },
        ),
        migrations.CreateModel(
            name='ZonaResidencia',
            fields=[
                ('id_zona_residencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_zona_residencia', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Zona_residencia',
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='municipio_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='zona_residencial',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='identidad_etnico_racial',
        ),
        migrations.AddField(
            model_name='persona',
            name='zona_residencia',
            field=models.ManyToManyField(blank=True, max_length=300, to='app_registro.zonaresidencia'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.ManyToManyField(blank=True, max_length=300, to='app_registro.estadocivil'),
        ),
        migrations.AddField(
            model_name='persona',
            name='identidad_etnico_racial',
            field=models.ManyToManyField(blank=True, max_length=300, to='app_registro.identidadetnicoracial'),
        ),
    ]
