# Generated by Django 5.0.7 on 2025-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0016_estadocivil_identidadetnicoracial_zonaresidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexoAsignado',
            fields=[
                ('id_sexo_asignado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sexo_asignado', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Sexo_asignado',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo_asignado',
            field=models.ManyToManyField(blank=True, max_length=300, to='app_registro.sexoasignado'),
        ),
    ]
