# Generated by Django 4.2.1 on 2023-06-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_registro', '0006_persona_ciudad_nacimiento_persona_ciudad_residencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosAutorizacion',
            fields=[
                ('id_documentos_autorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('autorizacion_manejo_de_datos', models.BooleanField()),
                ('firma_consentimiento_informado', models.BooleanField()),
                ('firma_terapia_hormonal', models.BooleanField(blank=True, null=True)),
                ('documento_digital_y_archivo', models.BooleanField(blank=True, null=True)),
                ('apgar_familiar', models.IntegerField()),
                ('ecomapa', models.BooleanField(blank=True, null=True)),
                ('arbol_familiar', models.BooleanField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_autorizacion', to='app_registro.persona')),
            ],
            options={
                'db_table': 'DocumentosAutorizacion',
            },
        ),
    ]
