# Generated by Django 4.2.1 on 2023-06-10 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0006_persona_ciudad_nacimiento_persona_ciudad_residencia_and_more'),
        ('app_documentos_autorizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosautorizacion',
            name='id_persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_autorizacion', to='app_registro.persona'),
        ),
    ]
