# Generated by Django 4.2.1 on 2023-06-10 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0006_persona_ciudad_nacimiento_persona_ciudad_residencia_and_more'),
        ('app_documentos_autorizacion', '0002_alter_documentosautorizacion_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosautorizacion',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_registro.persona'),
        ),
    ]
