# Generated by Django 4.2.1 on 2024-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos_autorizacion', '0004_alter_documentosautorizacion_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosautorizacion',
            name='apgar_familiar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentosautorizacion',
            name='autorizacion_manejo_de_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentosautorizacion',
            name='firma_consentimiento_informado',
            field=models.BooleanField(default=False),
        ),
    ]
