# Generated by Django 5.2 on 2025-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos_autorizacion', '0005_alter_documentosautorizacion_apgar_familiar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApgarPregunta1',
            fields=[
                ('id_apgar_pregunta1', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apgar_pregunta1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApgarPregunta2',
            fields=[
                ('id_apgar_pregunta2', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apgar_pregunta2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApgarPregunta3',
            fields=[
                ('id_apgar_pregunta3', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apgar_pregunta3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApgarPregunta4',
            fields=[
                ('id_apgar_pregunta4', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apgar_pregunta4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApgarPregunta5',
            fields=[
                ('id_apgar_pregunta5', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apgar_pregunta5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApgarPregunta6',
            fields=[
                ('id_apgar_pregunta6', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apgar_pregunta6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApgarPregunta7',
            fields=[
                ('id_apgar_pregunta7', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apgar_pregunta7', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='documentosautorizacion',
            name='apgar_pregunta1',
            field=models.ManyToManyField(blank=True, to='app_documentos_autorizacion.apgarpregunta1'),
        ),
        migrations.AddField(
            model_name='documentosautorizacion',
            name='apgar_pregunta2',
            field=models.ManyToManyField(blank=True, to='app_documentos_autorizacion.apgarpregunta2'),
        ),
        migrations.AddField(
            model_name='documentosautorizacion',
            name='apgar_pregunta3',
            field=models.ManyToManyField(blank=True, to='app_documentos_autorizacion.apgarpregunta3'),
        ),
        migrations.AddField(
            model_name='documentosautorizacion',
            name='apgar_pregunta4',
            field=models.ManyToManyField(blank=True, to='app_documentos_autorizacion.apgarpregunta4'),
        ),
        migrations.AddField(
            model_name='documentosautorizacion',
            name='apgar_pregunta5',
            field=models.ManyToManyField(blank=True, to='app_documentos_autorizacion.apgarpregunta5'),
        ),
        migrations.AddField(
            model_name='documentosautorizacion',
            name='apgar_pregunta6',
            field=models.ManyToManyField(blank=True, to='app_documentos_autorizacion.apgarpregunta6'),
        ),
        migrations.AddField(
            model_name='documentosautorizacion',
            name='apgar_pregunta7',
            field=models.ManyToManyField(blank=True, to='app_documentos_autorizacion.apgarpregunta7'),
        ),
    ]
