# Generated by Django 4.2.3 on 2024-10-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0002_monitoria_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoria_academica',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
