# Generated by Django 4.1.2 on 2023-06-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_programa', '0003_estado_programa_remove_programa_estudiante_estado_and_more'),
        ('modulo_instancia', '0006_delete_instancia'),
        ('modulo_usuario_rol', '0021_act_simultanea_cond_excepcion_discap_men_and_more'),
        ('modulo_academico', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('codigo', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='items_historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.curso')),
                ('id_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='items_semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.curso')),
                ('id_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('apellido', models.CharField(default=None, max_length=50)),
                ('correo', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='historial_academico',
            name='id_estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante'),
        ),
        migrations.AlterField(
            model_name='historial_academico',
            name='json_materias',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='notas_semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.items_semestre')),
            ],
        ),
        migrations.CreateModel(
            name='notas_historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.items_historico')),
            ],
        ),
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.curso')),
                ('id_estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='historial_academico_anterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_semestral', models.DecimalField(decimal_places=2, max_digits=3)),
                ('promedio_acumulado', models.DecimalField(decimal_places=2, max_digits=3)),
                ('json_materias', models.CharField(default=None, max_length=500)),
                ('id_programa_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_programa_estudiante_in_historial_academico_anterior', to='modulo_programa.programa_estudiante')),
                ('id_semestre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_semestre_in_historial_academico_anterior', to='modulo_instancia.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.profesores'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.sede'),
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre'),
        ),
    ]
