# Generated by Django 4.2 on 2023-06-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0006_delete_instancia'),
        ('modulo_usuario_rol', '0021_act_simultanea_cond_excepcion_discap_men_and_more'),
        ('modulo_academico', '0003_items_historico_items_semestre_profesor_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='items_historico',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('nombre', models.CharField(default=None, max_length=50)),
        #         ('nota_minima', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.materia')),
        #         ('id_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='items_semestre',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('nombre', models.CharField(default=None, max_length=50)),
        #         ('nota_minima', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.materia')),
        #         ('id_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.semestre')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='notas_semestre',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('id_estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
        #         ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.items_semestre')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='notas_historico',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('id_estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
        #         ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.items_historico')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='matricula',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.materia')),
        #         ('id_estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
        #     ],
        # ),
    ]
