# Generated by Django 4.1.2 on 2023-06-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0003_items_historico_items_semestre_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='id_profesor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.profesor'),
        ),
    ]
