# Generated by Django 6.1.1 on 2026-09-24 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0003_monitoria_academica_estado'),
        ('modulo_instancia', '0002_cohorte_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='horario_monitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=150)),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_monitor', to=settings.AUTH_USER_MODEL)),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_sede', to='modulo_instancia.sede')),
            ],
            options={
                'db_table': 'horario_monitoria',
            },
        ),
    ]
