# Generated by Django 4.1.2 on 2023-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0004_materia_id_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_academico',
            name='json_materias',
            field=models.JSONField(default=dict),
        ),
    ]
