# Generated by Django 4.1.2 on 2023-06-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0005_curso_franja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='franja',
        ),
        migrations.AddField(
            model_name='curso',
            name='ranja',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
