# Generated by Django 4.1.2 on 2023-06-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0005_alter_historial_academico_json_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_historico',
            name='id_profesor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.profesor'),
        ),
        migrations.AddField(
            model_name='items_semestre',
            name='id_profesor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.profesor'),
        ),
    ]
