# Generated by Django 4.1.2 on 2023-07-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0006_items_historico_id_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_historico',
            name='nota_maxima',
        ),
        migrations.RemoveField(
            model_name='items_historico',
            name='nota_minima',
        ),
        migrations.RemoveField(
            model_name='items_historico',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='items_semestre',
            name='nota_maxima',
        ),
        migrations.RemoveField(
            model_name='items_semestre',
            name='nota_minima',
        ),
        migrations.RemoveField(
            model_name='items_semestre',
            name='porcentaje',
        ),
    ]
