# Generated by Django 4.1.2 on 2023-06-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0006_remove_curso_franja_curso_ranja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='ranja',
            new_name='franja',
        ),
    ]
