# Generated by Django 4.1.2 on 2023-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0007_remove_items_historico_nota_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_historico',
            name='parcial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items_semestre',
            name='parcial',
            field=models.BooleanField(default=True),
        ),
    ]
