# Generated by Django 4.1.2 on 2023-06-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0007_rename_ranja_curso_franja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='franja',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
