# Generated by Django 4.1.2 on 2023-06-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_programa', '0003_estado_programa_remove_programa_estudiante_estado_and_more'),
        ('modulo_academico', '0008_alter_curso_franja'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_programa.facultad'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='franja',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
