# Generated by Django 4.1.2 on 2023-06-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0009_curso_programa_alter_curso_franja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='programa',
            new_name='facultad',
        ),
    ]
