# Generated by Django 4.1.2 on 2023-07-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0009_alter_items_historico_id_profesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id_curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.materia'),
        ),
    ]
