# Generated by Django 4.1.2 on 2023-06-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_programa', '0003_estado_programa_remove_programa_estudiante_estado_and_more'),
        ('modulo_academico', '0010_rename_programa_curso_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_academico_del_estudiante',
            name='id_programa_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_programa_in_historial_academico_del_estudiante', to='modulo_programa.programa'),
        ),
    ]
