# Generated by Django 4.1.2 on 2023-07-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0010_alter_matricula_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_semestre',
            name='id_curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.materia'),
        ),
        migrations.AlterField(
            model_name='items_semestre',
            name='parcial',
            field=models.BooleanField(default=False),
        ),
    ]
