# Generated by Django 4.1.2 on 2023-07-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_academico', '0011_alter_items_semestre_id_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_semestre',
            name='id_curso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_academico.materia'),
        ),
    ]
