# Generated by Django 4.2.4 on 2023-08-14 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_geografico', '0001_initial'),
        ('modulo_instancia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='act_simultanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=70)),
                ('opcion_general', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'act_simultanea',
            },
        ),
        migrations.CreateModel(
            name='cond_excepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond_excepcion', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cond_excepcion',
            },
        ),
        migrations.CreateModel(
            name='discap_men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_men', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'discap_men',
            },
        ),
        migrations.CreateModel(
            name='estado_civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etnia', models.CharField(max_length=70)),
                ('opcion_general', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'etnia',
            },
        ),
        migrations.CreateModel(
            name='identidad_gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
                ('opcion_general', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'identidad_gen',
            },
        ),
        migrations.CreateModel(
            name='permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='usuario_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='ACTIVO', max_length=30)),
                ('id_jefe', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe', to=settings.AUTH_USER_MODEL)),
                ('id_rol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol_por_asignar', to='modulo_usuario_rol.rol')),
                ('id_semestre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semestre_realizacion', to='modulo_instancia.semestre')),
                ('id_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='rol_permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permiso', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='permiso_por_asignar', to='modulo_usuario_rol.permiso')),
                ('id_rol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='modulo_usuario_rol.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
            },
        ),
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=30, null=True)),
                ('cod_univalle', models.CharField(max_length=12, unique=True)),
                ('num_doc', models.BigIntegerField(default=None, null=True)),
                ('dir_res', models.CharField(default=None, max_length=50, null=True)),
                ('sexo', models.CharField(max_length=20, null=True)),
                ('telefono', models.BigIntegerField(default=None, null=True)),
                ('celular', models.BigIntegerField(default=0, null=True)),
                ('acudiente', models.CharField(default=None, max_length=100, null=True)),
                ('telefono_acudiente', models.BigIntegerField(default=None, null=True)),
                ('fecha_nac', models.DateTimeField(null=True)),
                ('observacion', models.CharField(default=None, max_length=500, null=True)),
                ('anio_ingreso', models.DateTimeField(null=True)),
                ('ult_modificacion', models.DateTimeField(null=True)),
                ('barrio_res', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrio', to='modulo_geografico.barrio')),
                ('ciudad_res', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='modulo_geografico.municipio')),
                ('id_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitor',
            },
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('apellido', models.CharField(default=None, max_length=50)),
                ('cod_univalle', models.CharField(max_length=12, unique=True)),
                ('tipo_doc_ini', models.CharField(max_length=30)),
                ('num_doc_ini', models.BigIntegerField()),
                ('tipo_doc', models.CharField(max_length=30)),
                ('num_doc', models.BigIntegerField(default=None)),
                ('dir_ini', models.CharField(default=None, max_length=50)),
                ('telefono_ini', models.BigIntegerField(default=None)),
                ('dir_res', models.CharField(default=None, max_length=50)),
                ('telefono_res', models.BigIntegerField(default=None)),
                ('email', models.CharField(default=None, max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('colegio', models.CharField(default=None, max_length=60)),
                ('estamento', models.CharField(default=None, max_length=10)),
                ('estado_ases', models.BooleanField(default=True)),
                ('celular', models.BigIntegerField(default=0)),
                ('hijos', models.IntegerField(default=0)),
                ('acudiente', models.CharField(default=None, max_length=100)),
                ('telefono_acudiente', models.BigIntegerField(default=None)),
                ('fecha_nac', models.DateTimeField(null=True)),
                ('observacion', models.CharField(default=None, max_length=500, null=True)),
                ('vive_con', models.JSONField(default=dict, null=True)),
                ('anio_ingreso', models.DateTimeField(null=True)),
                ('actividades_ocio_deporte', models.CharField(default=None, max_length=200, null=True)),
                ('json_detalle', models.CharField(default=None, max_length=1000, null=True)),
                ('puntaje_icfes', models.IntegerField(default=None, null=True)),
                ('ult_modificacion', models.DateTimeField(null=True)),
                ('barrio_ini', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='barrio_inicial', to='modulo_geografico.barrio')),
                ('barrio_res', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='barrio_actual', to='modulo_geografico.barrio')),
                ('ciudad_ini', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_inicial', to='modulo_geografico.municipio')),
                ('ciudad_nac', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_nacimiento', to='modulo_geografico.municipio')),
                ('ciudad_res', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_actual', to='modulo_geografico.municipio')),
                ('id_act_simultanea', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_simultanea_in_estudiante', to='modulo_usuario_rol.act_simultanea')),
                ('id_cond_excepcion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cond_excepcion_in_estudiante', to='modulo_usuario_rol.cond_excepcion')),
                ('id_discapacidad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discap_men_in_estudiante', to='modulo_usuario_rol.discap_men')),
                ('id_estado_civil', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_civil_in_estudiante', to='modulo_usuario_rol.estado_civil')),
                ('id_etnia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etnia_in_estudiante', to='modulo_usuario_rol.etnia')),
                ('id_identidad_gen', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identidad_gen_in_estudiante', to='modulo_usuario_rol.identidad_gen')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='cohorte_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cohorte', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.cohorte')),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'cohorte_estudiante',
            },
        ),
    ]
