# Generated by Django 4.0 on 2022-06-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='bussinesses',
        ),
    ]
