# Generated by Django 4.2.6 on 2023-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cod_univalle',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
