# Generated by Django 4.2.4 on 2023-08-14 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.RegexValidator(message='Por favor ingresa un teléfono o celular valido', regex='^[()\\-0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_acudiente',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.RegexValidator(message='Por favor ingresa un teléfono o celular valido', regex='^[()\\-0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_ini',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.RegexValidator(message='Por favor ingresa un teléfono o celular valido', regex='^[()\\-0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_res',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.RegexValidator(message='Por favor ingresa un teléfono o celular valido', regex='^[()\\-0-9\\s]+$')]),
        ),
    ]
