# Generated by Django 4.2.6 on 2023-10-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='es_discapacidad',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
