# Generated by Django 4.1 on 2023-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0002_estudiante_es_discapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='encuesta_admitido',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
