# Generated by Django 4.2.4 on 2023-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0002_alter_estudiante_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estamento',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
