# Generated by Django 4.2.6 on 2023-10-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0002_alter_estudiante_cod_univalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cod_univalle',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
