# Generated by Django 4.0 on 2023-11-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0003_estudiante_encuesta_admitido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma_tratamiento_datos',
            old_name='autoriza',
            new_name='autoriza_tratamiento_datos',
        ),
        migrations.AddField(
            model_name='firma_tratamiento_datos',
            name='autoriza_tratamiento_imagen',
            field=models.BooleanField(default=False),
        ),
    ]
