# Generated by Django 4.0 on 2022-06-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0004_permiso_rol_usuario_rol_rol_permiso_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_rol',
            name='id_rol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol_por_asignar', to='modulo_usuario_rol.rol'),
        ),
    ]
