# Generated by Django 4.0 on 2023-11-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0004_rename_autoriza_firma_tratamiento_datos_autoriza_tratamiento_datos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma_tratamiento_datos',
            name='tipo_id_estudiante',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
