# Generated by Django 4.2.4 on 2023-08-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0004_alter_estudiante_colegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dir_ini',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dir_res',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
