# Generated by Django 5.0.2 on 2024-03-11 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0005_alter_firma_tratamiento_datos_tipo_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma_tratamiento_datos',
            name='id_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante', unique=True),
        ),
    ]
