# Generated by Django 4.2.4 on 2023-08-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0005_alter_estudiante_dir_ini_alter_estudiante_dir_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='firma_tratamiento_datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateTimeField()),
                ('nombre_firma', models.CharField(default=None, max_length=50)),
                ('autoriza', models.BooleanField(default=False)),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'firma_tratamiento_datos',
            },
        ),
    ]
