# Generated by Django 4.1 on 2024-04-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_usuario_rol", "0006_alter_firma_tratamiento_datos_id_estudiante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firma_tratamiento_datos",
            name="id_estudiante",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="modulo_usuario_rol.estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="firma_tratamiento_datos",
            name="tipo_id_estudiante",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
