# Generated by Django 4.2.4 on 2023-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0006_firma_tratamiento_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma_tratamiento_datos',
            name='correo_firma',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
