# Generated by Django 4.0 on 2022-06-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_asignacion', '0003_alter_asignacion_id_usuario'),
        ('modulo_usuario_rol', '0007_alter_usuario_rol_id_jefe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
