# Generated by Django 4.1 on 2024-04-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "modulo_usuario_rol",
            "0007_alter_firma_tratamiento_datos_id_estudiante_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="estudiante",
            old_name="estado_ases",
            new_name="estudiante_elegible",
        ),
    ]
