# Generated by Django 4.2.3 on 2024-05-31 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0001_initial'),
        ('modulo_usuario_rol', '0008_rename_estado_ases_estudiante_estudiante_elegible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte_estudiante',
            name='id_cohorte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_cohorte_in_cohorte_estudiante', to='modulo_instancia.cohorte'),
        ),
        migrations.AlterField(
            model_name='cohorte_estudiante',
            name='id_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_estudiante_in_cohorte_estudiante', to='modulo_usuario_rol.estudiante'),
        ),
    ]
