# Generated by Django 4.0 on 2022-10-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0003_delete_cohorte_estudiante'),
        ('modulo_usuario_rol', '0009_estudiante_num_doc_alter_estudiante_acudiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_rol',
            name='id_semestre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semestre_realizacion', to='modulo_instancia.semestre'),
        ),
        migrations.CreateModel(
            name='cohorte_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cohorte', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.cohorte')),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'cohorte_estudiante',
            },
        ),
    ]
