# Generated by Django 4.1 on 2024-08-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_usuario_rol", "0009_alter_cohorte_estudiante_id_cohorte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="es_academico",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
