# Generated by Django 5.1.1 on 2024-11-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0010_estudiante_es_academico_estudiante_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='firma_existe',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
