# Generated by Django 4.0 on 2022-11-24 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modulo_instancia', '0004_semestre_estado'),
        ('modulo_usuario_rol', '0018_alter_usuario_rol_id_jefe'),
    ]

    operations = [
        migrations.CreateModel(
            name='instancia_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_instancia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.instancia')),
                ('id_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'instancia_usuario',
            },
        ),
    ]
