# Generated by Django 4.0 on 2022-11-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0019_instancia_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instancia_usuario',
        ),
    ]
