# Generated by Django 4.1.1 on 2023-05-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_geografico", "0001_initial"),
        ("modulo_usuario_rol", "0020_delete_instancia_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="act_simultanea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actividad", models.CharField(max_length=70)),
                ("opcion_general", models.IntegerField(default=None, null=True)),
            ],
            options={"db_table": "act_simultanea",},
        ),
        migrations.CreateModel(
            name="cond_excepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cond_excepcion", models.CharField(max_length=100)),
                ("alias", models.CharField(max_length=20)),
            ],
            options={"db_table": "cond_excepcion",},
        ),
        migrations.CreateModel(
            name="discap_men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo_men", models.IntegerField(default=None, null=True)),
            ],
            options={"db_table": "discap_men",},
        ),
        migrations.CreateModel(
            name="estado_civil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_civil", models.CharField(max_length=30)),
            ],
            options={"db_table": "estado_civil",},
        ),
        migrations.CreateModel(
            name="etnia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etnia", models.CharField(max_length=70)),
                ("opcion_general", models.IntegerField(default=None, null=True)),
            ],
            options={"db_table": "etnia",},
        ),
        migrations.CreateModel(
            name="identidad_gen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genero", models.CharField(max_length=50)),
                ("opcion_general", models.IntegerField(default=None, null=True)),
            ],
            options={"db_table": "identidad_gen",},
        ),
        migrations.AddField(
            model_name="estudiante",
            name="actividades_ocio_deporte",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="anio_ingreso",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="ciudad_nac",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ciudad_nacimiento",
                to="modulo_geografico.municipio",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="fecha_nac",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="json_detalle",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="observacion",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="puntaje_icfes",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="ult_modificacion",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="vive_con",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="id_act_simultanea",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="act_simultanea_in_estudiante",
                to="modulo_usuario_rol.act_simultanea",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="id_cond_excepcion",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cond_excepcion_in_estudiante",
                to="modulo_usuario_rol.cond_excepcion",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="id_discapacidad",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discap_men_in_estudiante",
                to="modulo_usuario_rol.discap_men",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="id_estado_civil",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estado_civil_in_estudiante",
                to="modulo_usuario_rol.estado_civil",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="id_etnia",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etnia_in_estudiante",
                to="modulo_usuario_rol.etnia",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="id_identidad_gen",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identidad_gen_in_estudiante",
                to="modulo_usuario_rol.identidad_gen",
            ),
        ),
    ]
