# Generated by Django 4.1.2 on 2023-06-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0006_delete_instancia'),
        ('modulo_usuario_rol', '0021_act_simultanea_cond_excepcion_discap_men_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante_cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cohorte', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_instancia.cohorte')),
                ('id_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.estudiante')),
            ],
            options={
                'db_table': 'estudiante_cohorte',
            },
        ),
    ]
