# Generated by Django 4.1.2 on 2023-06-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0022_estudiante_cohorte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estudiante_cohorte',
        ),
    ]
