# Generated by Django 4.1.2 on 2023-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0024_alter_estudiante_vive_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='vive_con',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
