# Generated by Django 4.1.1 on 2023-07-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_usuario_rol", "0024_alter_estudiante_vive_con"),
        ("modulo_usuario_rol", "0025_alter_estudiante_vive_con"),
    ]

    operations = []
