# Generated by Django 4.1.2 on 2023-07-30 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_geografico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_usuario_rol', '0025_alter_estudiante_vive_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50, null=True)),
                ('apellido', models.CharField(default=None, max_length=50, null=True)),
                ('cod_univalle', models.CharField(max_length=12, null=True, unique=True)),
                ('tipo_doc', models.CharField(max_length=30, null=True)),
                ('num_doc', models.BigIntegerField(default=None, null=True)),
                ('dir_res', models.CharField(default=None, max_length=50, null=True)),
                ('email', models.CharField(default=None, max_length=100, null=True)),
                ('sexo', models.CharField(max_length=20, null=True)),
                ('telefono', models.BigIntegerField(default=None, null=True)),
                ('celular', models.BigIntegerField(default=0, null=True)),
                ('acudiente', models.CharField(default=None, max_length=100, null=True)),
                ('telefono_acudiente', models.BigIntegerField(default=None, null=True)),
                ('fecha_nac', models.DateTimeField(null=True)),
                ('observacion', models.CharField(default=None, max_length=500, null=True)),
                ('vive_con', models.JSONField(default=dict, null=True)),
                ('anio_ingreso', models.DateTimeField(null=True)),
                ('ult_modificacion', models.DateTimeField(null=True)),
                ('barrio_res', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrio', to='modulo_geografico.barrio')),
                ('ciudad_res', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='modulo_geografico.municipio')),
                ('id_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitor',
            },
        ),
    ]
