# Generated by Django 4.2.3 on 2023-07-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0024_alter_estudiante_vive_con'),
        ('modulo_usuario_rol', '0025_alter_estudiante_vive_con'),
    ]

    operations = [
    ]
