# Generated by Django 4.1.2 on 2023-07-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0026_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='nombre',
        ),
    ]
