# Generated by Django 4.2.3 on 2023-07-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0026_merge_20230718_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='vive_con',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
