# Generated by Django 4.1.1 on 2023-07-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0026_merge_20230719_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='vive_con',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
