# Generated by Django 4.2.3 on 2023-07-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0027_alter_estudiante_vive_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cond_excepcion',
            name='cond_excepcion',
            field=models.CharField(max_length=200),
        ),
    ]
