# Generated by Django 4.1.2 on 2023-07-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0027_remove_monitor_apellido_remove_monitor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='cod_univalle',
        ),
    ]
