# Generated by Django 4.1.2 on 2023-07-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0029_remove_monitor_vive_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='cod_univalle',
            field=models.CharField(default=123, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
