# Generated by Django 4.2.3 on 2023-08-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario_rol', '0028_alter_cond_excepcion_cond_excepcion'),
        ('modulo_usuario_rol', '0030_monitor_cod_univalle'),
    ]

    operations = [
    ]
