# Generated by Django 4.0 on 2022-10-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_instancia', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cohorte_estudiante',
        ),
    ]
