# Generated by Django 4.1.1 on 2022-11-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo_instancia", "0003_delete_cohorte_estudiante"),
    ]

    operations = [
        migrations.AddField(
            model_name="semestre",
            name="estado",
            field=models.SmallIntegerField(default=0),
        ),
    ]
