# Generated by Django 6.0.2 on 2026-05-25 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuario_rol', '0011_estudiante_firma_existe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, editable=False, max_digits=4, verbose_name='Horas trabajadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.usuario_rol')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de horas',
                'verbose_name_plural': 'Registros de horas',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
    ]
