# Generated by Django 6.0.2 on 2026-05-05 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Inicio de semana')),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Horas trabajadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de horas',
                'verbose_name_plural': 'Registros de horas',
                'ordering': ['-semana_inicio'],
                'constraints': [models.UniqueConstraint(fields=('trabajador', 'semana_inicio'), name='unique_registro_por_trabajador_por_semana')],
            },
        ),
    ]
