# Generated by Django 6.0.2 on 2026-05-07 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_horas_trabajadas', '0001_initial'),
        ('modulo_usuario_rol', '0011_estudiante_firma_existe'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoras',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_usuario_rol.usuario_rol'),
        ),
    ]
