# Generated by Django 6.0.2 on 2026-06-13 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_horas_trabajadas', '0001_initial'),
        ('modulo_instancia', '0002_cohorte_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporadaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.PositiveSmallIntegerField(default=20, verbose_name='Horas semanales')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del trabajador en el semestre')),
                ('fecha_fin', models.DateField(blank=True, help_text='Si está vacío, se usa la fecha de fin del semestre', null=True, verbose_name='Fecha de fin del trabajador en el semestre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas_trabajo', to='modulo_instancia.semestre')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporada de trabajo',
                'verbose_name_plural': 'Temporadas de trabajo',
                'unique_together': {('trabajador', 'semestre')},
            },
        ),
    ]
