# Generated by Django 6.0.2 on 2026-06-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_horas_trabajadas', '0002_temporadatrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporadatrabajo',
            name='horas_total_contratadas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Toras totales contatadas en semestre'),
        ),
        migrations.AddField(
            model_name='temporadatrabajo',
            name='precio_hora',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio hora'),
        ),
    ]
