# Generated by Django 6.0.2 on 2026-06-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_horas_trabajadas', '0003_temporadatrabajo_horas_total_contratadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporadatrabajo',
            name='total_festivos_temporada',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='numero de festivos en temporada'),
        ),
    ]
