# Generated by Django 6.0.2 on 2026-06-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_horas_trabajadas', '0004_temporadatrabajo_total_festivos_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporadatrabajo',
            name='is_default',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporadatrabajo',
            name='horas_total_contratadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Toras totales contatadas en semestre'),
        ),
    ]
